#!/bin/bash
# Correctly setup the domain hostname

source common

HOSTNAME=`hostname`

echo
echo "Hostname is currently '$HOSTNAME'"
echo "Please enter the domain name of this system or enter to accept this"
echo "e.g. mywebsite.com"
echo

NEWHOSTNAME=`INIT ask --prompt "Hostname" --var "PROFILE_HOSTNAME"`

if [ "$HOSTNAME" != "$NEWHOSTNAME" ]; then
	INIT status "Change server hostname"
	sudo hostname "$NEWHOSTNAME"
	echo "$NEWHOSTNAME" | sudo tee /etc/hostname >/dev/null
fi
