#!/bin/bash
# Correctly setup the timezone

source common

SYS_TIMEZONE=`cat /etc/timezone`

echo
echo "Timezone is currently '$SYS_TIMEZONE'"
echo "Please enter the the correct timezone of this system or enter to accept this"
echo "e.g. Australia/Brisbane"
echo

TIMEZONE=`INIT ask --prompt "Timezone" --var "PROFILE_TIMEZONE" --default "$SYS_TIMEZONE"`

if [ -z "$TIMEZONE" ]; then
	exit 0
fi

if [ "$TIMEZONE" != "$SYS_TIMEZONE" ]; then
	INIT status "Change server timezone ${SYS_TIMEZONE} -> ${TIMEZONE}"
	sudo timedatectl set-timezone "$TIMEZONE"
	sudo /etc/init.d/cron restart
	timedatectl
fi
