#!/bin/bash
# Fix the stupid Ubuntu behaviour where each apt install fires the "Daemons Needs Restart" dialog

source common

if [ -e '/etc/needrestart/needrestart.conf' ]; then
	init status "Fixing NeedsRestart config"
	# Taken from https://askubuntu.com/a/1421221/53688
	sudo sed -i 's/#$nrconf{restart} = '"'"'i'"'"';/$nrconf{restart} = '"'"'a'"'"';/g' /etc/needrestart/needrestart.conf
fi
