#!/bin/bash
# Correctly setup the timezone

source common

TIMEZONE=`cat /etc/timezone`

echo
echo "Timezone is currently '$TIMEZONE'"
echo "Please enter the the correct timezone of this system or enter to accept this"
echo "e.g. Australia/Brisbane"
echo

read -p "Timezone [$TIMEZONE] >" NEWTIMEZONE

echo

if [ -z "$NEWTIMEZONE" ]; then
	exit 0
fi

if [ "$TIMEZONE" != "$NEWTIMEZONE" ]; then
	INIT status "Change server timezone"
	sudo timedatectl set-timezone "$NEWTIMEZONE"
	sudo /etc/init.d/cron restart
	timedatectl
fi
