#!/bin/bash
# Fix the stupid Ubuntu behaviour where each apt install fires the "Daemons Needs Restart" dialog

source common

INIT apt-remove --lazy --header "Remove loud reboot notifier" --mode purge needrestart
