#!/bin/bash
# Generates the initial RSA identity of this server

source common

if [ -e "$HOME/.ssh/id_rsa" ]; then
	echoStatus "RSA key already genereated. Skip"
	exit 0
fi

echoStatus "Generate RSA key"
ssh-keygen -f "$HOME/.ssh/id_rsa" -t rsa -N ''
