#!/bin/bash
# Fix the stupid issue on Ubuntu where locales don't get set right because Australia is on another world or something
source common

init apt-install --lazy --header "Install locales prerequisites" dialog locales

init status "Setting Australian locale correctly"
sudo locale-gen en_US en_US.UTF-8
sudo locale-gen en_AU en_AU.UTF-8
sudo dpkg-reconfigure -f noninteractive locales
