#!/bin/bash
# Disable plain-text password logins

source common

INIT status "Denying plain-text password logins"
sudo perl -pi -e 's/^PasswordAuthentication yes$/PasswordAuthentication no/g' /etc/ssh/sshd_config


INIT status "Reloading SSHD"
sudo service ssh reload

