#!/bin/bash
# Adjust swappiness (cache RAM usage) for OS's that really care about total RAM used

source common

init status "Releasing cache memory"
sudo sysctl -w vm.drop_caches=3


init status "Adjusting swappiness"
# Lower swappiness = cache agressively in RAM, higher = swap to disk more (use less cache RAM)
sudo sysctl vm.swappiness=80

echo 'vm.swappiness=80' | sudo tee -a /etc/sysctl.conf >/dev/null
