#!/bin/bash
# Reduce the log size of JournalCtl down to something usable (Defaults to 4gb if not-run)

source common

INIT status "Limiting JournalCtl log size to 64mb"
INIT config-set /etc/systemd/journald.conf 'SystemMaxUse' '64M'


INIT status "Vacuum existing JournalCtl logs"
sudo journalctl --vacuum-size=64M
