#!/bin/bash
# Disable plain-text password logins

source common

echoStatus "Denying plain-text password logins"
sudo perl -pi -e 's/^PasswordAuthentication yes$/PasswordAuthentication no/g' /etc/ssh/sshd_config


echoStatus "Reloading SSHD"
sudo service sshd reload

