#!/bin/bash
# Set up a 4gb swap file using disk storage
#
# NOTE: Use `free -h` to see swap file usage

source common

SWAP_SIZE=2G
SWAP_FILE="/var/swap-$(echo "$SWAP_SIZE" | tr '[:upper:]' '[:lower:]').img"


INIT status "Setting up ${SWAP_SIZE} Swap file"
sudo touch "${SWAP_FILE}"
sudo chmod 0600 "${SWAP_FILE}"
sudo fallocate -l "${SWAP_SIZE}" "${SWAP_FILE}"
sudo truncate "${SWAP_FILE}" --size="${SWAP_SIZE}"
sudo mkswap "${SWAP_FILE}"
sudo swapon "${SWAP_FILE}"

INIT file-set --append /etc/fstab <<EOF
${SWAP_FILE}    none    swap    sw    0    0
EOF
