#!/bin/bash
# Disable plain-text password logins

source common

init status "Denying plain-text password logins"
sudo perl -pi -e 's/^PasswordAuthentication yes$/PasswordAuthentication no/g' /etc/ssh/sshd_config


init status "Reloading SSHD"
sudo service sshd reload

