#!/bin/bash
# Patch overly agressive Ulimits

source "$(dirname "${BASH_SOURCE[0]}")/./common"

INIT status "Adjust system limits..."

INIT file-set --append /etc/security/limits.conf <<EOF
root            soft    nproc           62188
root            hard    nproc           62188
root            hard    memlock         64
root            soft    sigpending      62188
root            hard    sigpending      62188
EOF
