#!/bin/bash
# Set filesystem journaling to non-crazy limits and purge existing cache

source common

INIT status "Limiting JournalCtl log size to 64mb"
INIT config-set /etc/systemd/journald.conf 'SystemMaxUse' '64M'


INIT status "Vacuum existing JournalCtl logs"
sudo journalctl --vacuum-size=64M

INIT status "Restart JournalD"
sudo systemctl restart systemd-journald
