#!/bin/bash
# Set up a 1gb swap file using disk
# This is only really useful on Minimal-RAM systems

source common

echoStatus "Setting up Swap file"
sudo touch /var/swap.img
sudo chmod 0600 /var/swap.img
sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
sudo mkswap /var/swap.img
sudo swapon /var/swap.img
echo "/var/swap.img    none    swap    sw    0    0" | sudo tee -a /etc/fstab >/dev/null


echoStatus "Setting up system Swappiness"
sudo sysctl -w vm.swappiness=30
