#!/bin/bash
# Removes unneeded default Ubuntu packages

source common

INIT apt-remove --lazy --mode purge --header "Remove Postfix" postfix

INIT apt-remove --lazy --mode purge --header "Remove silly media players" \
	banshee \
	gmusicbrowser \
	parole \
	rhythmbox \


INIT apt-remove --lazy --mode purge --header "Remove usless crash loggers" \
	apport-symptoms \
	whoopsie \
	zeitgeist \
	zeitgeist-* \


INIT apt-remove --lazy --mode purge --header "Remove stupid APT indexer for Unity / Ubuntu package manager" \
	apt-xapian-index \


INIT apt-remove --lazy --mode purge --header "Remove Ubuntu telemetry" \
	popularity-contest \


INIT apt-remove --lazy --mode purge --header "Remove heavy non-server packages" \
	abiword \


INIT status "Cleanup orphaned APT packages"
sudo apt autoremove -y --purge
