#!/bin/bash
# Various fixes for very small VMs
# Mainly this is just Swap file hacks so NPM doesn't kill itself when searching in <512mb RAM

source common

echoStatus "Minimal Server Setup"
read -p "Is this server a tiny VM server with RAM < 512mb? (y|n) " SETUP
echo

if [ "$SETUP" != "y" ]; then
	exit 0
fi

# Size in GB of the swap file to set up. Must be a whole number
# Webpack faults if total RAM size is less than 4gb so 4 is a good number here
SIZEGB=4

echoStatus "Setting up ${SIZEGB}gb Swap file"
sudo touch /var/swap-${SIZEGB}gb.img
sudo chmod 0600 /var/swap-${SIZEGB}gb.img
sudo dd if=/dev/zero of=/var/swap-${SIZEGB}gb.img bs=1024k count=${SIZEGB}000
sudo mkswap /var/swap-${SIZEGB}gb.img
sudo swapon /var/swap-${SIZEGB}gb.img
echo "/var/swap-${SIZEGB}gb.img    none    swap    sw    0    0" | sudo tee -a /etc/fstab >/dev/null


echoStatus "Setting up system Swappiness"
sudo sysctl -w vm.swappiness=30
