#!/bin/bash
# Removes unneeded default Ubuntu packages

source common

init status "Remove silly media players"
sudo apt purge -y rhythmbox banshee abiword parole gmusicbrowser

init status "Remove usless crash loggers"
sudo apt purge -y zeitgeist zeitgeist-* whoopsie apport-symptoms

init status "Remove stupid APT indexer for Unity / Ubuntu package manager"
sudo apt purge -y apt-xapian-index

init status "Remove Ubuntu telemetry"
sudo apt purge -y popularity-contest

init status "Cleanup orphaned APT packages"
sudo apt autoremove -y --purge
