#!/bin/bash
# Various fixes for Digital Ocean minimal VMs
# Mainly this is just Swap file hacks so NPM doesn't kill itself when searching in <512mb RAM

source common

read -p "Is this server a minimal Digital Ocean server (i.e. RAM =< 500mb)? (y|n) " SETUP
echo

if [ "$SETUP" != "y" ]; then
	exit 0
fi


echoStatus "Setting up Swap file"
sudo touch /var/swap.img
sudo chmod 0600 /var/swap.img
sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
sudo mkswap /var/swap.img
sudo swapon /var/swap.img
echo "/var/swap.img    none    swap    sw    0    0" | sudo tee -a /etc/fstab >/dev/null

echoStatus "Setting up system Swappiness"
sudo sysctl -w vm.swappiness=30
