#!/bin/bash
# Various fixes for very small VMs
# Mainly this is just Swap file hacks so NPM doesn't kill itself when searching in <512mb RAM

source common

echoStatus "Minimal Server Setup"
read -p "Is this server a tiny VM server with RAM < 512mb? (y|n) " SETUP
echo

if [ "$SETUP" != "y" ]; then
	exit 0
fi


echoStatus "Setting up Swap file"
sudo touch /var/swap.img
sudo chmod 0600 /var/swap.img
sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
sudo mkswap /var/swap.img
sudo swapon /var/swap.img
echo "/var/swap.img    none    swap    sw    0    0" | sudo tee -a /etc/fstab >/dev/null


echoStatus "Setting up system Swappiness"
sudo sysctl -w vm.swappiness=30
