#!/bin/bash
# Enables partner repos

source common

INIT status "Enable partner APT sources"
if [ ! -e '/etc/apt/sources.list' ]; then
	INIT skip "Not a Debian based distro"
else
	sudo perl -pi -e 's/^# (.* partner)$/\1/g' /etc/apt/sources.list
fi
