#!/bin/bash
# Install packages suitable for use as a desktop platform.

source common

INIT status "Install desktop APT packages"
INIT apt-install \
	audacity  \
	audacious \
	bmon \
	easytag \
	etherape \
	filelight \
	file-roller \
	flameshot \
	gdebi \
	geeqie \
	giggle \
	gftp \
	gimp \
	gimp-plugin-registry \
	gparted \
	gthumb \
	gweled \
	gwenview \
	htop \
	git \
	git-lfs \
	ffmpeg \
	ffmpegthumbs \
	ffmpegthumbnailer \
	mplayer \
	numlockx \
	openssh-server \
	libreoffice \
	pulseaudio-module-bluetooth \
	sshuttle \
	vlc \
	wireshark \
	wmctrl \
	xbindkeys \
	xclip \
	xmacro \
	xscreensaver-data \
	xscreensaver-data-extra \
	xscreensaver-gl \
	xscreensaver-gl-extra \
	xsel \
