#!/bin/bash
# Install desktop theme packages

source common

echoStatus "Install desktop theme PPA - Plata"
sudo add-apt-repository -y ppa:tista/plata-theme


echoStatus "Install all theme packages"
./utils/apt-install \
	arc-theme \
	oxygen-cursor-theme \
	plata-theme \
