#!/bin/bash
# Install all auto-updating APT security packages
# REQUIRES: 007-apt-update

source common

INIT status "Install Auto-update APT packages"
INIT apt-install \
	cron-apt \
	software-properties-common \
	unattended-upgrades \

