#!/bin/bash
# Install all auto-updating APT security packages

source "$(dirname "${BASH_SOURCE[0]}")/./common"

INIT status "Install Auto-update APT packages"
INIT apt-install --ignore-missing \
	cron-apt \
	software-properties-common \
	unattended-upgrades \

