#!/bin/bash
# Install desktop theme packages

source common

init status "Install desktop theme PPA - Plata"
sudo add-apt-repository -y ppa:tista/plata-theme


init status "Install all theme packages"
init apt-install \
	arc-theme \
	oxygen-cursor-theme \
	plata-theme \
