#!/bin/bash
# Install all auto-updating APT security packages
# REQUIRES: 007-apt-update

source common

echoStatus "Install Server APT packages"
sudo apt install -y \
cron-apt \
unattended-upgrades \

