#!/bin/bash
# Install packages suitable for use as a server

source common

INIT status "Remove Server unsuitable APT packages"

sudo apt-get remove -y \
samba


INIT status "Install Server APT packages"
INIT apt-install --ignore-missing \
	autossh \
	bmon \
	build-essential \
	bzip2 \
	curl \
	dos2unix \
	duc \
	expect \
	ftp \
	htop \
	git \
	git-lfs \
	glances \
	html2ps \
	iftop \
	imagemagick \
	iotop \
	libterm-readkey-perl \
	lftp \
	lsof \
	make \
	mc \
	molly-guard \
	moreutils \
	mutt \
	ncftp \
	ncat \
	net-tools \
	nmap \
	ntp \
	openssl \
	perl \
	pv \
	pwgen \
	rclone \
	screen \
	slurm \
	shellcheck \
	sshfs \
	sshpass \
	tar \
	tcpdump \
	telnet \
	tmux \
	tofrodos \
	traceroute \
	vim \
	w3m \
	wget \
	whois \

