#!/bin/bash
# Install packages suitable for use as a desktop platform.
# REQUIRES: 007-apt-update

source common

echoStatus "Install desktop APT packages"
init apt-install \
audacity  \
audacious \
bmon \
conky \
easytag \
etherape \
firefox \
filelight \
file-roller \
flameshot \
gdebi \
geeqie \
giggle \
gftp \
gimp \
gimp-plugin-registry \
gparted \
gthumb \
gweled \
gwenview \
htop \
git \
git-lfs \
k3b \
krename \
liquidwar \
luola \
luola-nostalgy \
ffmpeg \
ffmpegthumbs \
ffmpegthumbnailer \
meld \
mplayer \
numlockx \
openssh-server \
libreoffice \
pdfshuffler \
pidgin \
pidgin-extprefs \
pidgin-plugin-pack \
pidgin-themes \
pulseaudio-module-bluetooth \
sshuttle \
synergy \
vlc \
wireshark \
wmctrl \
xbindkeys \
xclip \
xmacro \
xscreensaver-data \
xscreensaver-data-extra \
xscreensaver-gl \
xscreensaver-gl-extra \
xsel \
