#!/bin/bash
# Install desktop theme packages

source common

INIT status "Install desktop theme PPA - Plata"
sudo add-apt-repository -y ppa:tista/plata-theme


INIT status "Install all theme packages"
INIT apt-install \
	arc-theme \
	oxygen-cursor-theme \
	plata-theme \
