#!/bin/bash
# Install PHP-Pear modules
# REQUIRES: 007-apt-update

source common

echoStatus "Install PHP-Pear"
sudo apt-get install -y php-pear

echoStatus "Install common Pear modules"

sudo pear install \
PhpDocumentor \


