#!/bin/bash
# Install tmux@latest from source

source common

echoStatus "Installing prerequisites"
./utils/apt-install \
	autoconf \
	automake \
	byacc \
	libevent-dev \
	libncurses-dev pkg-config \


echoStatus "Downloading Tmux"
./utils/source-clone tmux https://github.com/tmux/tmux.git


echoStatus "Building Tmux"
sh autogen.sh
./configure
make
sudo cp tmux /usr/bin/tmux
