#!/bin/bash
# Install Kodi modules
# REQUIRES: 007-apt-update

source common

init status "Install Kodi PPA"
sudo add-apt-repository -y ppa:team-xbmc/ppa

init status "Update APT"
sudo apt-get update

init status "Update Kodi via APT"
init apt-install kodi
