#!/bin/bash
# Install PHP-Pear modules
# REQUIRES: 007-apt-update

echo "* Install PHP-Pear..."
sudo apt-get install -y php-pear

echo "* Installing common Pear modules..."

sudo pear install \
PhpDocumentor \


