#!/bin/bash
# Secure the Port Scan protection

source "$(dirname "${BASH_SOURCE[0]}")/./common"


INIT apt-install --lazy --header "Install PSAD prerequisites" iptables
INIT apt-install --lazy --header 'Install PSAD' psad


if [ `INIT file-grep-matches /etc/psad/psad.conf 'daemons@mfdc.io'` == 0 ]; then
	INIT status "Configure PSAD"
	sudo perl -pi -e 's/(EMAIL_ADDRESSES\s+).*$/${1}daemons\@mfdc\.io;/g' /etc/psad/psad.conf
	sudo perl -pi -e "s/(HOSTNAME\s+).+$/\${1}$(hostname);/" /etc/psad/psad.conf
	sudo perl -pi -e 's/(EMAIL_THROTTLE\s+)0/${1}30/' /etc/psad/psad.conf
	sudo perl -pi -e 's/(ALERT_ALL\s+)N/${1}Y/' /etc/psad/psad.conf
	sudo perl -pi -e 's/(EMAIL_ALERT_DANGER_LEVEL\s+)1/${1}3/' /etc/psad/psad.conf

	INIT status "Configure PSAD whitelist"
	echo -e '# MFDC office\n103.96.6.111     0;' | sudo tee -a /etc/psad/auto_dl >/dev/null
else
	INIT skip "Configure PSAD"
fi


INIT status "Restarting PSAD"
sudo systemctl restart psad
