#!/bin/bash
# Install packages specific to XFCE
# REQUIRES: 007-apt-update

source common

echoStatus "Install common XFCE modules"

sudo apt install -y \
ffmpegthumbnailer \
tumbler \
tumbler-plugins-extra \
xfce4-goodies \
xfce4-power-manager-plugins \


