#!/bin/bash
# Install packages needed for Compiz

source common

INIT status "Install Compiz + Compiz utilities"

INIT apt-install \
	compiz \
	compizconfig-settings-manager \
	compiz-plugins \
	compiz-plugins-default \
	compiz-plugins-extra \
	compiz-plugins-main \
	compiz-plugins-main-default \

