#!/bin/bash
# Install packages specific to XFCE
# REQUIRES: 007-apt-update

source common

echoStatus "Install common XFCE modules"

sudo apt-get install -y \
xfce4-goodies \
xfce4-mixer \
xfce4-power-manager-plugins 


