#!/bin/bash
# Install tmux@latest from source

source common

INIT apt-install --lazy --header "Installing Tmux prerequisites" \
	autoconf \
	automake \
	bison \
	build-essential \
	byacc \
	libevent-dev \
	libncurses-dev pkg-config \
	pkg-config \


INIT status "Downloading Tmux"
INIT source-clone tmux https://github.com/tmux/tmux.git


INIT status "Building Tmux"
sh autogen.sh
./configure

# Build the base Tmux binary
make

# Note: install-exec-hook installs the manpage
sudo make install install-exec-hook
