#!/bin/bash
# Install CPAN modules
# REQUIRES: 007-apt-update

source common

init status "Install CPAN"
init apt-install cpan


init status "Install CPAN base modules"
sudo cpan CPAN YAML Term::ReadLine::Perl Test::Exception


init status "Install common CPAN modules"
sudo cpan \
	Config::IniFiles \
	Data::Dump \
	Digest::MD5::File \
	File::Basename \
	File::DirWalk \
	File::Slurp \
	Getopt::Long \
	IMDB::Film \
	Number::Bytes::Human \
	Term::ReadKey \
	Text::Glob \


