#!/bin/bash
# Secure the SSH port against attacks
# REQUIRES: 010-apt-server

source common


echoStatus "Install Fail2Ban"

sudo apt-get install -y fail2ban


echoStatus "Add MFDC to Fail2Ban IP whitelist"

sudo perl -pi -e 's/^ignoreip = .*$/ignoreip = 127.0.0.1\/8 10.0.0.1\/24 120.29.45.0\/24 120.29.46.0\/24 120.29.47.0\/24 120.29.48.0\/24 120.29.49.0\/24 120.29.50.0\/24 120.29.51.0\/24 120.29.52.0\/24 120.29.53.0\/24 120.29.54.0\/24 120.29.55.0\/24/' /etc/fail2ban/jail.conf


echoStatus "Restarting Fail2Ban"
sudo /etc/init.d/fail2ban restart
