#!/bin/bash
# Install packages specific to Gnome
# REQUIRES: 007-apt-update

source common

echoStatus "Install common GNOME modules"

./utils/apt-install \
gnome-art \
gnome-netstatus-applet \
gnome-themes-extras \
nautilus-open-terminal \
timer-applet \


