#!/bin/bash
# Install Kodi modules
# REQUIRES: 007-apt-update

source common

echoStatus "Install Kodi PPA"
sudo add-apt-repository -y ppa:team-xbmc/ppa

echoStatus "Update APT"
sudo apt-get update

echoStatus "Update Kodi via APT"
sudo apt-get install -y kodi
