#!/bin/bash
# Install packages needed for Compiz
# REQUIRES: 007-apt-update

source common

echoStatus "Install Compiz + Compiz utilities"

sudo apt install -y \
compiz \
compizconfig-settings-manager \
compiz-plugins \
compiz-plugins-default \
compiz-plugins-extra \
compiz-plugins-main \
compiz-plugins-main-default \

