#!/bin/bash
# Install Google Chrome

source common

INIT status "Install Google Chrome PPA"
if [ -e '/etc/apt/sources.list.d/google.list' ]; then
	INIT skip "PPA already exists"
else
	INIT apt-install --lazy wget

	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google.list >/dev/null

	INIT status "Update APT"
	sudo apt-get update
fi

INIT status "Install Google Chrome"
INIT apt-install google-chrome-stable
