#!/bin/bash
# Install packages specific to XFCE

source "$(dirname "${BASH_SOURCE[0]}")/./common"

INIT status "Install common XFCE modules"
INIT apt-install \
	ffmpegthumbnailer \
	tumbler \
	tumbler-plugins-extra \
	xfce4-goodies \
	xfce4-power-manager-plugins \


