#!/bin/bash
# Install packages specific to Gnome
# REQUIRES: 007-apt-update

source common

init status "Install common GNOME modules"

init apt-install \
	gnome-art \
	gnome-netstatus-applet \
	gnome-themes-extras \
	nautilus-open-terminal \
	timer-applet \


