#!/bin/bash
# Install CPAN modules

echo "* Installing CPAN..."
sudo apt-get install -y cpan

echo "* Installing CPAN base modules..."
sudo cpan CPAN YAML Term::ReadLine::Perl Test::Exception

echo "* Installing CPAN common modules..."
sudo cpan \
Config::IniFiles \
Data::Dump \
Digest::MD5::File \
File::Basename \
File::DirWalk \
File::Slurp \
Getopt::Long \
IMDB::Film \
Number::Bytes::Human \
Term::ReadKey \
Text::Glob \


