#!/bin/bash
# Install packages needed for Compiz

echo "* Install Compiz + Compiz utilities..."

sudo apt-get install -y \
compiz \
compizconfig-settings-manager \
compiz-plugins \
compiz-plugins-default \
compiz-plugins-extra \
compiz-plugins-main \
compiz-plugins-main-default \

