#!/bin/bash
# Install Kodi modules
# REQUIRES: 007-apt-update

source common

INIT status "Install Kodi PPA"
sudo add-apt-repository -y ppa:team-xbmc/ppa

INIT status "Update APT"
sudo apt-get update

INIT status "Update Kodi via APT"
INIT apt-install kodi
