#!/bin/bash
# Install packages specific to Gnome
# REQUIRES: 007-apt-update

echo "* Install common GNOME modules..."

apt-get install -y \
gnome-art \
gnome-netstatus-applet \
gnome-themes-extras \
nautilus-open-terminal \
timer-applet \


