#!/bin/bash
# Install IO.js

source common

echoStatus "Install NodeSource GPG key"
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

echoStatus "Install PPA repo"
sudo sh -c "echo deb https://deb.nodesource.com/iojs_1.x utopic main \
>/etc/apt/sources.list.d/nodesource.list"

echoStatus "Update APT"
sudo apt-get update

echoStatus "Install io.js from APT"
sudo apt-get install -y iojs
