#!/bin/bash
# Install Mongo v4 (with WiredTiger storage engine)
# REQUIRES: 007-apt-update

source common

echoStatus "Install MongoDB Apt repo"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4


echoStatus "Install Mongo Deb source"
echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

# BUGFIX: Ignore the section in the Mongo install instructions about installing the SystemD service for Ubuntu 16.4 - its already there


echoStatus "Update Apt"
sudo apt-get update


echoStatus "Install Mongo prerequisites"
sudo apt-get install -y libcurl3

echoStatus "Install Mongo from Apt"
sudo apt-get install -y mongodb-org mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools

echoStatus "Patch Mongo to use WiredTiger storage engine"
grep -q 'engine: "wiredTiger"' /etc/mongod.conf
if [ "$?" != 0 ]; then
	# BUGFIX: For some reason Mongo doesn't default to WiredTiger as the storage engine. Despite what the install docs say
	sudo perl -pi -e 's/^#  engine:.*$/  engine: "wiredTiger"/' /etc/mongod.conf
fi


echoStatus "Disable Kernel hugepages"
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null

echoStatus "Disable Kernel hugepages (install into rc.local)"
echo "#!/bin/sh -e" | sudo tee /etc/rc.local
echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" | sudo tee -a /etc/rc.local
echo "echo never > /sys/kernel/mm/transparent_hugepage/defrag" | sudo tee -a /etc/rc.local
echo "exit 0" | sudo tee -a /etc/rc.local
sudo chmod +x /etc/rc.local


echoStatus "Enable Mongo at startup"
sudo systemctl enable mongod

echoStatus "Start Mongo service"
sudo service mongod start
