#!/bin/bash
# Install docker
# REQUIRES: 007-apt-update

source common

INIT apt-install --lazy --header "Install main linux image sources" linux-image-extra-`uname -r`


if [ -e '/etc/apt/sources.list.d/docker.list' ]; then
	INIT skip "PPA already installed"
else
	INIT status "Install Docker PPA key"
	sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

	INIT status "Add Docker PPA"
	sudo sh -c "echo deb http://get.docker.io/ubuntu docker main\
	> /etc/apt/sources.list.d/docker.list"

	INIT status "Update APT"
	sudo apt-get update
fi

INIT status "Install Docker from APT"
INIT apt-install docker.io git

INIT status "Adjust firewall policy to allow Docker"
INIT config-set /etc/default/ufw 'DEFAULT_FORWARD_POLICY' 'ACCEPT'

INIT status "Reload firewall"
sudo ufw reload
