#!/bin/bash
# Install IO.js

echo "* Installing NodeSource GPG key..."
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

echo "* Install PPA repo..."
sudo sh -c "echo deb https://deb.nodesource.com/iojs_1.x utopic main \
>/etc/apt/sources.list.d/nodesource.list"

echo "* Updating Apt..."
sudo apt-get update

echo "* Installing io.js..."
sudo apt-get install -y iojs
