#!/bin/bash
# Sets up the default firewall
# REQUIRES: 007-apt-update

source common

echoStatus "Install Firewall scripts"
apt-get install ufw -y

echoStatus "Configure Firewall"
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow http
ufw allow https

echoStatus "Enable Firewall"
sudo perl -pi -e 's/ENABLED=no/ENABLED=yes/g' /etc/ufw/ufw.conf
