#!/bin/bash
# Install Ansible
# REQUIRES: 

source common

echoStatus "Install Ansible PPA"
sudo add-apt-repository -y ppa:ansible/ansible


echoStatus "Update APT"
sudo apt-get update

echoStatus "Install Ansible"
./utils/apt-install ansible
