#!/bin/bash
# Install Node + common NPM packages
# REQUIRES: 007-apt-update

source common

echoStatus "Install NodeSource Apt PPA + Update Apt"
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

echoStatus "Update Apt"
sudo apt-get update

echoStatus "Install Node from Apt"
sudo apt-get install -y nodejs

echoStatus "Install common Node system Apt packages"
sudo apt-get install -y imagemagick graphicsmagick potrace

if [ -e "$HOME/.npmrc" ]; then
	echoSkip "NPM config already exists"
else
	echoStatus "Install NPM config"
	echo 'email=m@ttcarter.com' >~/.npmrc
	echo 'tmp=/tmp/npm' >>~/.npmrc
	echo 'bin-links=true' >>~/.npmrc
	echo 'save=true' >>~/.npmrc
	echo 'spin=false' >>~/.npmrc
	echo 'loglevel=http' >>~/.npmrc
	echo 'registry=http://registry.npmjs.org' >>~/.npmrc
fi

echoStatus "Upgrade NPM to latest"
sudo npm install -g npm@latest

echoStatus "Install common global NPMs"
sudo npm install -g \
coma \
devtool \
doop-cli \
fkill-cli \
gulp \
jscs \
jshint \
json-prettify \
lodash \
@momsfriendlydevco/repl \
mocha \
npm-up \
pm2 \


echoStatus "Set up symlinks"
sudo ln -s /usr/bin/json-prettify /usr/bin/json

echoStatus "Reset permissions on ~/.npm and /tmp/npm"
sudo chmod 0777 -R ~/.npm /tmp/npm

echoStatus "Permit Node to have port 80 access"
sudo apt-get install -y libcap2-bin
sudo setcap cap_net_bind_service=+ep /usr/bin/nodejs

echoStatus "Config Bower to STFU about usage reporting"
mkdir "$HOME/.config"
mkdir "$HOME/.config/configstore"
echo 'optOut: true' >"$HOME/.config/configstore/insight-bower.yml"
echo 'optOut: true' >"$HOME/.config/configstore/update-notifier-bower.yml"
echo '{"optOut": true}' >"$HOME/.config/configstore/insight-bower.json"
echo '{"optOut": true}' >"$HOME/.config/configstore/update-notifier-bower.json"

echoStatus "Setup NODE_ENV"
grep -q 'NODE_ENV' "$HOME/.bashrc"
if [ "$?" == 0 ]; then
	echoSkip "NODE_ENV already setup"
else
	echo "Installing NODE_ENV into ~/.bashrc, assuming 'production'"
	echo "export NODE_ENV=production" >>~/.bashrc
	export NODE_ENV=production
fi
