#!/bin/bash
# Install packages suitable for PHP web hosting
# REQUIRES: 007-apt-update

source common

echoStatus "Install LAMP stack packages"

sudo apt-get install -y \
apache2 \
libapache2-mod-php5 \
mysql-server \
php5 \
php5-cli \
php5-curl \
php5-gd \
php5-imagick \
php5-imap \
php5-mysql \
php-pear \


echoStatus "Install LAMP stack meta-package"

sudo apt-get install --force-yes -y lamp-server^
