#!/bin/bash
# Install MongoDB
# REQUIRES: 007-apt-update

source common

init status "Remove existing Mongo installs"
init apt-remove 'mongodb*'


# Patch LibSSL1.1 not being available on Ubuntu>22.04
if [ `dpkg -l 'libssl1.1*' >/dev/null; echo "$?"` == 0 ]; then
	init skip "LibSSL1.1 already installed or known"
else
	init status "Installing LibSSL1.1 for Ubuntu>=22.04"
	cd ~/src
	wget 'http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb'
	sudo dpkg -i libssl*.deb
	rm libssl*.deb
	cd
fi


init status "Download MongoDB DPKG"
cd
if [ ! -d 'src' ]; then
	mkdir src 2>/dev/null
fi
cd "$HOME/src"
wget \
	https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/5.0/multiverse/binary-amd64/mongodb-org-server_5.0.8_amd64.deb \
	https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/5.0/multiverse/binary-amd64/mongodb-org-shell_5.0.8_amd64.deb \
	https://downloads.mongodb.com/compass/mongodb-mongosh_1.1.2_amd64.deb \
	https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.5.1.deb


init status "Install MongoDB DPKGs"
sudo dpkg -i mongodb-*.deb
rm *.deb


if [ `grep -q 'engine: "wiredTiger"' /etc/mongod.conf; echo "$?"` != 0 ]; then
	init status "Patch Mongo to use WiredTiger storage engine"
	# BUGFIX: For some reason Mongo doesn't default to WiredTiger as the storage engine. Despite what the install docs say
	sudo perl -pi -e 's/^#  engine:.*$/  engine: "wiredTiger"/' /etc/mongod.conf
fi

if [ -f "/etc/logrotate.d/mongodb" ]; then
	init skip "Setup Logrotate (already exists)"
else
	init status "Setup Logrotate"
	# Add logRotate option to reopen on rotate
	init snap-install yq
	yq '.systemLog.logRotate="reopen"' </etc/mongod.conf | sudo sponge /etc/mongod.conf

cat <<'EOF' | sudo tee -a /etc/logrotate.d/mongodb >/dev/null
/var/log/mongodb/mongod.log {
  daily
  size 128M
  rotate 7
  missingok
  nocompress
  notifempty
  create 600 mongodb mongodb
  sharedscripts
  postrotate
    /usr/bin/pkill -SIGUSR1 mongod
  endscript
}
EOF
	sudo systemctl restart logrotate
fi


init status "Disable Kernel hugepages"
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null


init status "Disable Kernel hugepages (install into rc.local)"
echo "#!/bin/sh -e" | sudo tee /etc/rc.local
echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" | sudo tee -a /etc/rc.local
echo "echo never > /sys/kernel/mm/transparent_hugepage/defrag" | sudo tee -a /etc/rc.local
echo "exit 0" | sudo tee -a /etc/rc.local
sudo chmod +x /etc/rc.local


init status "Enable Mongo at startup"
sudo systemctl enable mongod


init status "Start Mongo service"
sudo systemctl start mongod


init status "Wait for Mongo service to come up"
sleep 3


init status "Disable Mongo monitoring"
/usr/bin/mongo --eval 'db.disableFreeMonitoring()'
