#!/bin/bash
# Install Mongo v4 (with WiredTiger storage engine)
# REQUIRES: 007-apt-update

source common

echoStatus "Download MongoDB DPKG"
cd
mkdir src 2>/dev/null
cd src
wget \
	https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.7_amd64.deb \
	https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-tools_4.2.7_amd64.deb \
	https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-shell_4.2.7_amd64.deb \


echoStatus "Install MongoDB DPKGs"
sudo dpkg -i mongodb-*.deb
rm *.deb


echoStatus "Patch Mongo to use WiredTiger storage engine"
grep -q 'engine: "wiredTiger"' /etc/mongod.conf
if [ "$?" != 0 ]; then
	# BUGFIX: For some reason Mongo doesn't default to WiredTiger as the storage engine. Despite what the install docs say
	sudo perl -pi -e 's/^#  engine:.*$/  engine: "wiredTiger"/' /etc/mongod.conf
fi


echoStatus "Disable Kernel hugepages"
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null


echoStatus "Disable Kernel hugepages (install into rc.local)"
echo "#!/bin/sh -e" | sudo tee /etc/rc.local
echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" | sudo tee -a /etc/rc.local
echo "echo never > /sys/kernel/mm/transparent_hugepage/defrag" | sudo tee -a /etc/rc.local
echo "exit 0" | sudo tee -a /etc/rc.local
sudo chmod +x /etc/rc.local


echoStatus "Enable Mongo at startup"
sudo systemctl enable mongod


echoStatus "Start Mongo service"
sudo service mongod start


echoStatus "Wait for Mongo service to come up"
sleep 3


echoStatus "Disable Mongo monitoring"
/usr/bin/mongo --eval 'db.disableFreeMonitoring()'
