#!/bin/bash
# Sets up the default firewall
# REQUIRES: 007-apt-update

source common

init status "Install Firewall scripts"
init apt-install ufw -y

init status "Disable FirewallD"
sudo systemctl disable firewalld

init status "Configure Firewall"
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https

init status "Enable Firewall"
sudo perl -pi -e 's/ENABLED=no/ENABLED=yes/g' /etc/ufw/ufw.conf
sudo ufw --force enable
