#!/bin/bash
# Install MongoDB

source common

# Mongo versions to attempt
VERSION_SERVER=7.0.5
VERSION_SHELL=2.1.1
VERSION_COMPASS=1.41.0

INIT apt-remove --lazy --header "Remove existing Mongo installs" 'mongodb*'


INIT apt-install-url \
	"https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/7.0/multiverse/binary-amd64/mongodb-org-server_${VERSION_SERVER}_amd64.deb" \
	"https://downloads.mongodb.com/compass/mongodb-mongosh_${VERSION_SHELL}_amd64.deb" \
	"https://downloads.mongodb.com/compass/mongodb-compass_${VERSION_COMPASS}_amd64.deb" \
	"https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.5.1.deb" \


if [ -f "/etc/logrotate.d/mongodb" ]; then
	INIT skip "Setup Logrotate (already exists)"
else
	INIT status "Setup Logrotate for Mongo"

	INIT apt-install --lazy logrotate

	# Add logRotate option to reopen on rotate
	INIT snap-install yq
	yq '.systemLog.logRotate="reopen"' </etc/mongod.conf | sudo sponge /etc/mongod.conf

INIT file-set /etc/logrotate.d/mongodb <<EOF
/var/log/mongodb/mongod.log {
  daily
  size 128M
  rotate 7
  missingok
  nocompress
  notifempty
  create 600 mongodb mongodb
  sharedscripts
  postrotate
    /usr/bin/pkill -SIGUSR1 mongod
  endscript
}
EOF
	sudo systemctl restart logrotate
fi


INIT status "Disable Kernel hugepages"
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null


INIT status "Disable Kernel hugepages (install into rc.local)"
INIT file-set /etc/rc.local <<EOF
#!/bin/sh -e
echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo never > /sys/kernel/mm/transparent_hugepage/defrag
exit 0
EOF

sudo chmod +x /etc/rc.local


INIT status "Enable Mongo at startup"
sudo systemctl enable mongod


INIT status "Start Mongo service"
sudo systemctl start mongod


INIT status "Wait for Mongo service to come up"
sleep 3


INIT status "Disable Mongo monitoring"
/usr/bin/mongosh --eval 'db.disableFreeMonitoring()'
