#!/bin/bash
# Install Node + common NPM packages
# REQUIRES: 007-apt-update

source common

echoStatus "Install NodeSource Apt PPA + Update Apt"
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

echoStatus "Install Node from Apt"
sudo apt-get install -y nodejs

echoStatus "Install common Node system Apt packages"
sudo apt-get install -y imagemagick graphicsmagick potrace

if [ -e "$HOME/.npmrc" ]; then
	echoSkip "NPM config already exists"
else
	echoStatus "Install NPM config"
	echo 'email=m@ttcarter.com' >~/.npmrc
	echo 'tmp=/tmp/npm' >>~/.npmrc
	echo 'bin-links=true' >>~/.npmrc
	echo 'save=true' >>~/.npmrc
	echo 'spin=false' >>~/.npmrc
	echo 'loglevel=http' >>~/.npmrc
	echo 'registry=http://registry.npmjs.org' >>~/.npmrc
fi

echoStatus "Upgrade NPM to latest"
sudo npm install -g npm@latest

echoStatus "Install common global NPMs"
sudo npm install -g \
coma \
doop-cli \
fkill-cli \
fx \
gronk \
gulp \
jaywalker \
jscs \
jshint \
json-prettify \
mocha \
@momsfriendlydevco/cli-snip \
@momsfriendlydevco/repl \
npm-up \
pm2 \


if [ -e /usr/bin/json-prettify ]; then
	echoSkip "JSON prettifier already exists as /usr/bin/json"
else
	echoStatus "Set up symlinks"
	sudo ln -s /usr/bin/json-prettify /usr/bin/json
fi

echoStatus "Reset permissions on ~/.npm and /tmp/npm"
sudo chmod 0777 -R ~/.npm /tmp/npm

echoStatus "Permit Node to have port 80 access"
sudo apt-get install -y libcap2-bin
sudo setcap cap_net_bind_service=+ep /usr/bin/node

echoStatus "Setup NODE_ENV"
grep -q 'NODE_ENV' "$HOME/.bashrc"
if [ "$?" == 0 ]; then
	echoSkip "NODE_ENV already setup"
else
	echo "Installing NODE_ENV into ~/.bashrc, assuming 'production'"
	echo "export NODE_ENV=production" >>~/.bashrc
	export NODE_ENV=production
fi
