#!/bin/bash
# Sets up the default firewall

source common

if [ `INIT service-available firewalld` == 1 ]; then
	INIT status "Disable FirewallD (conflicts with UFW)"
	sudo systemctl disable firewalld
fi

INIT status "Install Firewall scripts"
INIT apt-install ufw


INIT status "Configure Firewall"
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https


INIT status "Enable Firewall"
INIT config-set /etc/ufw/ufw.conf 'ENABLED' 'yes'

INIT status "Start Firewall"
sudo ufw --force enable
