#!/bin/bash
# Install Mongo v3 (with WiredTiger storage engine)
# REQUIRES: 007-apt-update

source common

echoStatus "Install MongoDB Apt repo"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927


echoStatus "Install Mongo Deb source"
echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

# BUGFIX: Ignore the section in the Mongo install instructions about installing the SystemD service for Ubuntu 16.4 - its already there


echoStatus "Update Apt"
sudo apt-get update


echoStatus "Install Node from Apt"
sudo apt-get install -y mongodb-org


# Has it already installed its upstart job?
if [ -f "/etc/init/mongod.conf" ]; then
	echoStatus "Stop Mongo service"
	sudo service mongod stop
else
	echoStatus "Installing Upstart job"
# Upstart job {{{
cat <<EOF | sudo tee /etc/init/mongod.conf >/dev/null
# Ubuntu upstart file at /etc/init/mongod.conf

limit nofile 20000 20000

kill timeout 300 # wait 300s between SIGTERM and SIGKILL.

pre-start script
	mkdir -p /var/lib/mongodb/
	mkdir -p /var/log/mongodb/
end script

start on runlevel [2345]
stop on runlevel [06]

script
	exec start-stop-daemon --make-pidfile --pidfile /var/run/mongodb.pid --start --quiet --chuid mongodb --exec  /usr/bin/mongod -- --config /etc/mongod.conf
end script
EOF
# }}}

	echoStatus "Installing Init.D script"
	sudo ln -s /lib/init/upstart-job /etc/init.d/mongod
fi



echoStatus "Patch Mongo to use WiredTiger storage engine"
# BUGFIX: For some reason Mongo3 doesn't default to WiredTiger as the storage engine. Despite what the install docs say
sudo perl -pi -e 's/^#  engine:.*$/  engine: "wiredTiger"/' /etc/mongod.conf


echoStatus "Move Mongo storage directory (to use WiredTiger storage engine)"
# BUGFIX: We also have to change the dbpath for some reason or Mongo still uses the wrong engine
sudo perl -pi -e 's/^  dbPath:.*$/  dbPath: \/var\/lib\/mongodb.wt/' /etc/mongod.conf
sudo mkdir /var/lib/mongodb.wt
sudo chown mongodb:mongodb /var/lib/mongodb.wt


echoStatus "Disable Kernel hugepages"
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
echo never | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null

# Set into rc.local so it also applies on restart
echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" >/etc/rc.local
echo "echo never > /sys/kernel/mm/transparent_hugepage/defrag" >>/etc/rc.local
echo "exit 0"


echoStatus "Start Mongo service"
sudo service mongod start
