#!/bin/bash
# Install IO.js

source common

if [ -e '/etc/apt/sources.list.d/nodesource.list' ]; then
	echoSkip "NodeSource PPA already installed"
else
	echoStatus "Install NodeSource GPG key"
	curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

	echoStatus "Install PPA repo"
	echo 'deb https://deb.nodesource.com/iojs_1.x utopic main' | sudo tee -a '/etc/apt/sources.list.d/nodesource.list' >/dev/null

	echoStatus "Update APT"
	sudo apt-get update
fi

echoStatus "Install io.js from APT"
sudo apt-get install -y iojs
