#!/bin/bash
# Install Cordova packages

echo "Install the PPA for Cordova..."
sudo apt-add-repository ppa:cordova-ubuntu/ppa
sudo apt-get update

echo "Installing Cordova..."
sudo apt-get install -y cmake debhelper libx11-dev libicu-dev pkg-config qtbase5-dev qtchooser qtdeclarative5-dev qtfeedback5-dev qtlocation5-dev qtmultimedia5-dev qtpim5-dev qtsensors5-dev qtsystems5-dev
sudo apt-get install -y cordova-cli
sudo npm install -g cordova
