#!/bin/bash
# Install Cordova packages

source common

init status "Install Cordova PPA"
sudo apt-add-repository ppa:cordova-ubuntu/ppa
sudo apt-get update

init status "Install Cordova from APT"
init apt-install \
   cmake \
   cordova \
   cordova-cli \
   debhelper \
   libx11-dev \
   libicu-dev \
   pkg-config \
   qtbase5-dev \
   qtchooser \
   qtdeclarative5-dev \
   qtfeedback5-dev \
   qtlocation5-dev \
   qtmultimedia5-dev \
   qtpim5-dev \
   qtsensors5-dev \
   qtsystems5-dev \

