#!/bin/bash
# Setup a basic mail server, redirecting email to another address
# Change the default relays at the bottom of this file as needed
# REQUIRES: 000-hostname

source common

HOSTNAME=`hostname`

echoStatus "Install Postfix from APT"
sudo apt-get install -y postfix

if [ -e '/etc/postfix/virtual' ]; then
	echoSkip "Postfix virtual file already exists"
else
	echoStatus "Set up Postfix virtuals config"
	echo "virtual_alias_domains = $HOSTNAME" | sudo tee -a /etc/postfix/main.cf >/dev/null
	echo "virtual_alias_maps = hash:/etc/postfix/virtual" | sudo tee -a /etc/postfix/main.cf >/dev/null

	echoStatus "Set up mail redirects"
	echo "info@$HOSTNAME		matt@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "root@$HOSTNAME		matt@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "admin@$HOSTNAME		matt@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "administrator@$HOSTNAME	matt@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "webmaster@$HOSTNAME		matt@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "hostmaster@$HOSTNAME	matt@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "mc@$HOSTNAME		matt@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "matt@$HOSTNAME		matt@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "vandy@$HOSTNAME		vandy@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "mark@$HOSTNAME		mark@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "jake@$HOSTNAME		jake@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null
	echo "charles@$HOSTNAME		charles@mfdc.biz" | sudo tee -a /etc/postfix/virtual >/dev/null


	echoStatus "Compile redirects database"
	sudo postmap /etc/postfix/virtual

	echoStatus "Restart postfix"
	sudo /etc/init.d/postfix restart
fi
