#!/bin/bash
# Install the latest XScreensaver package

source common

init status "Install XScreensaver PPA"
sudo add-apt-repository -y ppa:savoury1/xscreensaver

init status "Install XScreensaver components"
init apt-install xscreensaver xscreensaver-screensaver-bsod xscreensaver-gl xscreensaver-gl-extra xscreensaver-data xscreensaver-data-extra
