#!/bin/bash
# Fix the MOTD on Ubuntu to STFU

source common

echoStatus "Blank the MOTD"
echo "" | sudo tee /etc/motd.tail >/dev/null
echo "" | sudo tee /etc/motd >/dev/null

echoStatus "Disable all UpdateMotd scripts"
if [ -f /etc/ssh/sshd_banner ]; then
	sudo rm /etc/ssh/sshd_banner
fi

sudo rm /etc/update-motd.d/* || true
