#!/bin/bash
# Creates a symlink to the /var/www Apache web directory in the users home dir
# Also wipes the existing /var/www clean
# REQUIRES: pkg:apache2

source common

echoStatus "Clear /var/www"
sudo rm -r /var/www
sudo mkdir /var/www
chmod 0777 -R /var/www

echoStatus "Create symlink to /var/www"
cd
ln -s /var/www www
