#!/bin/bash
# Configure apache based on the usual MFDC settings

echo "* Patching PHP config..."
sudo perl -pi -e 's/^display_errors = .*$/display_errors = On/g' /etc/php5/apache2/php.ini
sudo perl -pi -e 's/^short_open_tag = .*$/short_open_tag = On/g' /etc/php5/apache2/php.ini

echo "* Patching Apache config..."
sudo perl -pi -e 's/DocumentRoot \/var\/www\/html/DocumentRoot \/var\/www/g' /etc/apache2/sites-available/*default*
sudo perl -pi -e 's/<\/VirtualHost>/\t<Directory "\/var\/www">\n\t\tAllowOverride all\n\t<\/Directory>\n<\/VirtualHost>/' /etc/apache2/sites-available/*default*

echo "* Enabling common modules..."
sudo ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load
sudo ln -s /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled/headers.load

echo "* Restarting Apache..."
sudo service apache2 restart
