#!/bin/bash
# Creates a symlink to the /var/www Apache web directory in the users home dir
# Also wipes the existing /var/www clean
# REQUIRES: pkg:apache2

echo "* Clearing /var/www..."
sudo rm -r /var/www
sudo mkdir /var/www
chmod 0777 -R /var/www

echo "* Creating symlink to /var/www..."
cd
ln -s /var/www www
