#!/bin/bash
# Setup screen config

source "$(dirname "${BASH_SOURCE[0]}")/./common"

INIT status "Patch Screen config"
INIT config-set /etc/screenrc 'startup_message' 'off'
INIT config-set /etc/screenrc 'vbell' 'off'
