#!/bin/bash
# Set the current users default shell to ZSH
# REQUIRES: 007-apt-update

source common

echoStatus "Install ZSH"
sudo apt install -y zsh


echoStatus "Set shell"
sudo chsh "$USER" -s /bin/zsh
sudo chown -R "$USER:$USER" "$HOME/.zsh"
