#!/bin/bash
# Set the current users default shell to ZSH
# REQUIRES: 007-apt-update

source common

init status "Install ZSH"
init apt-install zsh


init status "Set shell"
sudo chsh "$USER" -s /bin/zsh
sudo chown -R "$USER:$USER" "$HOME/.zsh"
