#!/bin/bash
# Link all dot files in ~/Papers/Dots

source common

echoStatus "Link host dependent files"
if [ -d "$HOME/Papers/Dots/Hosts/$HOSTNAME" ]; then
	ln -s ~/Papers/Dots/Hosts/`hostname`/.??* .
	echoStatus "Link SSH Config"
	ln -s ~/Papers/Dots/Hosts/`hostname`/SSH-Config ~/.ssh/config
else
	echo "!!!!! WARNING - CANNOT LINK TO NONE EXISTANT HOST DIR ~/Papers/Dots/Hosts/$HOSTNAME !!!!!"
	echo "Exiting!"
	exit 1
fi

echoStatus "Link all dot files"
cd
rm ~/.bashrc ~/.vimrc
ln -s ~/Papers/Dots/.??* .
ln -s ~/Papers/Notes/Notes.txt ~/notes
ln -s ~/Papers/Scripts ~/Scripts

echoStatus "Link config files"
cd
mkdir .config
cd .config
ln -s ~/Papers/Dots/config/* .
cd

echoStatus "Link Gnome-art"
ln -s ~/Papers/Dots/Special/gnome-art ~/.gnome2/gnome-art

echoStatus "Install mount-papers Script"
cp ~/Papers/Scripts/mount-papers ~

echoStatus "Install Nautilus Scripts"
ln -s ~/Papers/Dots/nautilus-scripts ~/.gnome2/nautilus-scripts
