#!/bin/bash
# Set the current users default shell to ZSH
# REQUIRES: 007-apt-update

source common

INIT status "Install ZSH"
INIT apt-install zsh


INIT status "Set shell"
sudo chsh "$USER" -s /bin/zsh
sudo chown -R "$USER:$USER" "$HOME/.zsh"
