#!/bin/bash
# Setup Pidgin correctly
# This script assumes you already have a pre-bundled Pidgin install

source common

PIDGIN_INSTALL="$HOME/Papers/Dots/Templates/Pidgin.tar.bz2"

echoStatus "Set up Pidgin"
mkdir ~/.purple
cd ~/.purple
if [ -d "logs" ]; then
	echo "!!!! WARNING ~/.purple/logs is ALREADY a directory. It should be a link to ~/Papers/Logs. It may need merging manually !!!!"
else
	ln -s ~/Papers/Logs logs
fi
if [ -d "icons" ]; then
	echo "!!!! WARNING ~/.purple/icons is ALREADY a directory. It should be a link to ~/Papers/Logs/Icons. It may need merging manually !!!!"
else
	ln -s ~/Papers/Logs/Icons icons
fi
if [ -d "certificates" ]; then
	echo "Certificates directory already exists. Avoiding setting up Pidgin template install"
else
	tar xvfj "$PIDGIN_INSTALL"
fi
