#!/bin/bash
# Install the Neovim Nightly from source
# REQUIRES: 007-apt-update

source common

echoStatus "Install Redis PPA"
sudo add-apt-repository -y ppa:redislabs/redis

echoStatus "Installing Redis Server"
sudo apt install -y redis
