#!/bin/bash
# Install `monit` service monitor which keeps Apache, MySQL and Postfix running

source common

INIT status "Install monit from APT"
INIT apt-install monit

grep -q "daemons@mfdc.io" /etc/monit/monitrc
if [ "$?" == 0 ]; then
	INIT skip "Monit already configured"
else
	INIT status "Config Monit"
	sudo perl -pi -e 's/set daemon 120/set daemon 30/' /etc/monit/monitrc

	# Enable HTTP UI (needed for CLI command to work) {{{
INIT file-set /etc/monit/monitrc <<EOF
# Send alerts to daemons@mfdc.io
set alert daemons@mfdc.io
set mailserver localhost

# Enable Monit HTTP interface so CLI commands work
set httpd port 2812 and
    use address localhost  # only accept connection from localhost
    allow localhost        # allow localhost to connect to the server and
EOF
	# }}}

	INIT status "Setup MongoDB Monit profile"
	# Add MongoDB profile {{{
INIT file-set /etc/monit/conf-available/mongodb <<EOF
check process mongodb with pidfile /var/lib/mongodb.wt/mongod.lock

group database

start program = "/bin/systemctl start mongodb"
stop program = "/bin/systemctl stop mongodb"

if failed host localhost port 27017 then restart
EOF
	# }}}

	sudo ln -s /etc/monit/conf-available/mongodb /etc/monit/conf-enabled/mongodb

	INIT status "Restart Monit"
	sudo service monit restart
fi
