#!/bin/bash
# Install `monit` service monitor which keeps Apache, MySQL and Postfix running
# REQUIRES: 007-apt-update

source common

echoStatus "Install monit from APT"
sudo apt-get install -y monit

echoStatus "Config monit"
echo 'set httpd port 2812 and' | tee -a '/etc/monit/monitrc'
echo 'use address localhost' | tee -a '/etc/monit/monitrc'
echo 'allow localhost' | tee -a '/etc/monit/monitrc'
echo '' | tee -a '/etc/monit/monitrc'
echo 'include /etc/monit/monitrc.d/mysql' | tee -a '/etc/monit/monitrc'
echo 'include /etc/monit/monitrc.d/apache2' | tee -a '/etc/monit/monitrc'
echo 'include /etc/monit/monitrc.d/postfix' | tee -a '/etc/monit/monitrc'

echoStatus "Restart monit"
sudo /etc/init.d/monit restart
