#!/bin/bash
# Install NewRelic monitors for PHP

source common

echoStatus "Instal NewRelic PPA"
wget -O - https://download.newrelic.com/548C16BF.gpg | sudo apt-key add -
sudo sh -c 'echo "deb http://apt.newrelic.com/debian/ newrelic non-free" >/etc/apt/sources.list.d/newrelic.list'

echoStatus "Update APT"
sudo apt-get update

echoStatus "Install NewRelic deamon"
sudo apt-get install -y newrelic-php5

echoStatus "Set up NewRelic"
sudo newrelic-install install

echoStatus "Restart Apache"
sudo /etc/init.d/apache2 restart
