#!/bin/bash
# Install Neovim
# REQUIRES: 007-apt-update

source common

dpkg -l | grep -q neovim
if [ "$?" == 0 ]; then
	echoSkip "NeoVim already installed"
	exit 0
fi

echoStatus "Install Neovim PPA"
sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo apt update
sudo apt install -y neovim


echoStatus "Install Python3 worker"
sudo apt install -y python3 python3-pip
sudo pip3 install neovim


echoStatus "Set alternate linking for vi / vim / editor"
NVIM=`which nvim`
sudo update-alternatives --install /usr/bin/vi vi $NVIM 60
sudo update-alternatives --config vi
sudo update-alternatives --install /usr/bin/vim vim $NVIM 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor $NVIM 60
sudo update-alternatives --config editor


echoStatus "Link config directories"
cd
ln -s .vimrc .nvimrc
ln -s .vim .nvim
