#!/bin/bash
# Creates the ~/Papers directory as an EncFS mount point
# REQUIRES: pkg:encfs

echo "* Setting up encrypted ~/Papers directory..."

if [ -d "$HOME/Papers" ]; then
	echo "~/Papers is already setup (or mounted)"
	exit 1
else
	echo "~/Papers is not setup correctly."
	echo "Installing EncFS..."
	sudo apt-get install -y encfs
	mkdir ~/.Papers
	echo "Attempting to mount papers"
	cd
	sudo encfs "$HOME/.Papers" "$HOME/Papers" -- -o allow_other,uid=1000
	echo "Done"
	echo
	echo "~/Papers is now setup as an encrypted area for Papers."
	echo "Copy all files into this directory before continuing"
	echo
fi
