#!/bin/bash
# Install Neovim LSP / Language Server Protocol support

source common

INIT status "Install Language servers (JS/NPM)"
INIT npm-install -g \
	@vue/language-server \
	lehre \
	typescript \
	typescript-language-server \
	vscode-langservers-extracted \


INIT status "Install Language servers (Rust/Cargo)"
INIT cargo-install \
	just-lsp \


