#!/bin/bash
# Install NewRelic monitors for PHP

source common

if [ -e '/etc/apt/sources.list.d/newrelic.list' ]; then
	echoSkip "NewRelic PPA already installed"
else
	echoStatus "Install NewRelic PPA"
	wget -O - https://download.newrelic.com/548C16BF.gpg | sudo apt-key add -
	sudo sh -c 'echo "deb http://apt.newrelic.com/debian/ newrelic non-free" >/etc/apt/sources.list.d/newrelic.list'

	echoStatus "Update APT"
	sudo apt-get update
fi

echoStatus "Install NewRelic deamon"
sudo apt-get install -y newrelic-php5

echoStatus "Restart Apache"
sudo /etc/init.d/apache2 restart
