#!/bin/bash
# Install the Redis Client + Server from source

source common

INIT apt-remove --lazy --header "Remove Redis APT distributions" redis redis-tools redis-server

INIT apt-install --lazy --header "Install Redis build dependencies" libsystemd-dev

INIT status "Download Redis source"
INIT source-clone redis https://github.com/redis/redis.git
INIT go-src redis


INIT status "Build Redis from source"
make clean
make distclean
make USE_SYSTEMD=yes MALLOC=jemalloc


INIT status "Testing Redis install"
make test

INIT status "Finalizing Redis install"
sudo make install


INIT status "Installing Redis as a service"
sudo mkdir /etc/redis
sudo cp redis.conf /etc/redis

INIT fixme "Need to check if Redis correctly installs SystemD setup as 'redis-server' here - if so remove this fixme"
sudo systemctl enable redis-server
sudo systemctl start redis-server

INIT status "Configuring Redis Server"
# Active degragging tries to clear up memory fragmentation periodically
redis-cli config set activedefrag yes

# Commit Redis config to disk
redis-cli config rewrite
