#!/bin/bash
# Install Neovim
# REQUIRES: 007-apt-update

source common

dpkg -l | grep -q neovim
if [ "$?" == 0 ]; then
	echoSkip "NeoVim already installed"
else
	echoStatus "Install Neovim PPA"
	sudo add-apt-repository -y ppa:neovim-ppa/unstable
	sudo apt update
	sudo apt install -y neovim


	echoStatus "Install Python3 worker"
	sudo apt install -y python3 python3-pip
	sudo pip3 install neovim


	echoStatus "Set alternate linking for vi / vim / editor"
	NVIM=`which nvim`
	sudo update-alternatives --install /usr/bin/vi vi $NVIM 60
	sudo update-alternatives --config vi
	sudo update-alternatives --install /usr/bin/vim vim $NVIM 60
	sudo update-alternatives --config vim
	sudo update-alternatives --install /usr/bin/editor editor $NVIM 60
	sudo update-alternatives --config editor
fi

if [ !-e "~/.vim/setup" ]; then
	echoStatus "Setup MC Nvim config"
	cd
	git clone https://github.com/hash-bang/vimrc.git .vim
	mkdir -p .config/nvim 2>/dev/null
	ln -s .vim/init.vim .config/nvim/init.vim
	~/.vim/setup
else
	echoStatus "Update MC Nvim config"
	cd ~/.vim
	git pull
	~/.vim/setup
fi
