#!/bin/bash
# Install the FZF binaries for Shell + Vim usage
# REQUIRES: 007-apt-update
#
# NOTE: This installs the source rather than the PPA (ppa:neovim-ppa/unstable)
#	as that seems not to actually be a Nightly build
#       - MC 2021-06-16

source common

./utils/source-clone fzf https://github.com/junegunn/fzf.git

echoStatus "Building FZF"
./install --key-bindings --completion --update-rc
