#!/bin/bash
# Setup any /etc config files

source common

echoStatus "Install PATH into root users .bashrc"
echo "PATH=$PATH:/inc/scripts/hosts/`hostname`:/inc/scripts/users/`whoami`:/inc/scripts" | sudo tee -a /root/.bashrc >/dev/null
