#!/bin/bash
# Install the `dtrx` swiss-army-knife extrator
# REQUIRES: 007-apt-update

source common

echoStatus "Install DTRX prerequisites"
init apt-install python2

init source-clone dtrx https://github.com/brettcs/dtrx.git

echoStatus "Build + install DTRX"
sudo python2 setup.py install
