#!/bin/bash
# Install Neovim LSP / Language Server Protocol support

source "$(dirname "${BASH_SOURCE[0]}")/./common"

INIT status "Install Language servers (JS/NPM)"
INIT npm-install -g \
	@vue/language-server \
	lehre \
	typescript \
	typescript-language-server \
	vscode-langservers-extracted \

