#!/bin/bash
# Install the Redis Client + Server from source

source common

INIT apt-remove --lazy --header "Remove Redis APT distributions" redis redis-tools redis-server

INIT apt-install --lazy --header "Install Redis build dependencies" libsystemd-dev

INIT status "Download Redis source"
INIT source-clone redis https://github.com/redis/redis.git
INIT go-src redis


INIT status "Build Redis from source"
make clean
make distclean
make USE_SYSTEMD=yes MALLOC=jemalloc


INIT status "Testing Redis install"
make test

INIT status "Finalizing Redis install"
sudo make install

INIT status "Setup redis config"
sudo mkdir /etc/redis
sudo cp redis.conf /etc/redis

if [ ! -f "/etc/systemd/system/redis.service"; then
	INIT status "Setup Redis as a SystemD service"

INIT file-set /etc/systemd/system/redis.service <<EOF
[Unit]
Description=Redis
After=syslog.target

[Service]
ExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf
RestartSec=5s
Restart=on-success

[Install]
WantedBy=multi-user.target
EOF

	sudo systemctl daemon-reload
	sudo systemctl start redis-server
	sudo systemctl enable redis-server
else
	INIT skip "Setup Redis as a SystemD service"
fi


INIT status "Configuring Redis Server"
# Active degragging tries to clear up memory fragmentation periodically
redis-cli config set activedefrag yes

# Commit Redis config to disk
redis-cli config rewrite
