#!/bin/bash
# Setup Gnome to use the &#$%!# Bond University Proxy
# REQUIRES: 015-apt-gnome

source common

echoStatus "Set Gnome proxy"
gconftool-2 -t string -s /system/proxy/mode "manual"
gconftool-2 -t string -s /system/proxy/secure_host "Bondproxy.bond.edu.au"
gconftool-2 -t int -s /system/proxy/secure_port "8080"
gconftool-2 -t string -s /system/http_proxy/host "Bondproxy.bond.edu.au"
gconftool-2 -t int -s /system/http_proxy/port "8080"
