#!/bin/bash
# Install S3FS from source

source common

echoStatus "Remove conflicting S3FS packages"
# mlocate (the updated deamon) tends to crash S3FS when it tries to cache the FS structure of infinite filesystems like S3
sudo apt-get remove -y s3fs mlocate


echoStatus "Install S3FS build tools"
init apt-install \
	automake \
	autotools-dev \
	fuse \
	g++ \
	git \
	libcurl4-gnutls-dev \
	libfuse-dev \
	libssl-dev \
	libxml2-dev \
	make \
	pkg-config \


echoStatus "Download S3FS source"
init source-clone s3fs https://github.com/s3fs-fuse/s3fs-fuse.git


echoStatus "Compile S3FS"
./autogen.sh
./configure
make
sudo make install
