#!/bin/bash
# Install LetsEncrypt for a single site

source common

# Check if letsencrypt is already installed
if [ `INIT bin-available certbot` == 1 ]; then
	INIT skip "LetsEncrypt is already installed"
else
	INIT status "Install LetsEncrypt"
	INIT snap-install --classic certbot
	sudo snap set certbot trust-plugin-with-root=ok

	INIT status "Install DME LetsEncrypt plugin"
	INIT snap-install --beta certbot-dns-dnsmadeeasy
fi
