#!/bin/bash
# Install LetsEncrypt for a single site

source common

# Check if letsencrypt is already installed
cd
if [ -e "certbot-auto" ]; then
	echoSkip "LetsEncrypt is already installed"
else
	echoStatus "Install LetsEncrypt"
	sudo apt install -y snapd
	sudo snap install --classic certbot
	sudo snap set certbot trust-plugin-with-root=ok
	sudo snap install --beta certbot-dns-dnsmadeeasy
fi
