#!/bin/bash
# Install Tailscale networking

source "$(dirname "${BASH_SOURCE[0]}")/./common"

if [ `INIT bin-available tailscale` == 1 ]; then
	INIT skip "Install Tailscale"
else
	INIT apt-install --lazy curl

	INIT status "Install Tailscale"
	curl -fsSL https://tailscale.com/install.sh | sh
fi
