#!/bin/bash
# Install Rust / Cargo + common Cargo packages
# REQUIRES: 007-apt-update

source common

init status "Install / Upgrade Rust"
init bin-download-run 'https://sh.rustup.rs' -y


init status "Install Cargo prerequisites"
init apt-install \
	cmake \
	libasound2-dev \
	libclang1 \
	libssl-dev \
	libfreetype6-dev \
	libexpat1-dev \
	libxcb-composite0-dev \
	pkg-config \


init status "Install common Cargo tools"
source "$HOME/.cargo/env"
init cargo-install \
	bat \
	bandwhich \
	bottom \
	diffr \
	du-dust \
	exa \
	fd-find \
	git-delta \
	hexyl \
	jless \
	lfs \
	lsd \
	mcfly \
	tokei \
	xcp \


init status "Install Dog"
init cargo-install --git https://github.com/ogham/dog dog


init status "Install RipGrep + PCRE2 support"
init cargo-install ripgrep --features pcre2
