#!/bin/bash
# Install QGIS

source common

INIT apt-install wget --lazy --header "Install QGIS prefequisites"

if [ ! -e "/etc/apt/sources.list.d/qgis.sources" ]; then
	INIT status "Install QGIS keyring + apt repo"
	sudo wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg

	SUITES=`lsb_release -cs`

INIT file-set /etc/apt/sources.list.d/qgis.sources <<EOF
Types: deb deb-src
URIs: https://qgis.org/debian
Suites: ${SUITES}
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg
EOF
else
	INIT skip "Install QGIS keyring + apt repo"
fi


INIT status "Install QGIS"
INIT apt-update
INIT apt-install qgis
