#!/bin/bash
# Install Flatpak + basic packages

source common

if [ `INIT bin-available flatpak` == 1 ]; then
	INIT skip "Install Flatpak"
	INIT apt-install flatpak

	INIT skip "Configure Flathub"
	flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
else
	INIT status "Install Flatpak"
fi

INIT status "Installing Flatpak packages"

FLATPAK_PKGS='
	org.gnome.meld   # "meld" - pretty diffs and meld tool
'
FLATPAK_PKGS=`echo "$FLATPAK_PKGS" | cut -f 1 -d ' ' | tr '\n' ' '`

sudo flatpak install flathub $FLATPAK_PKGS
