#!/bin/bash
# Install Rust / Cargo + common Cargo packages
# REQUIRES: 007-apt-update

source common

echoStatus "Install / Upgrade Rust"
wget 'https://sh.rustup.rs' -O /tmp/rustup.rs
chmod +x /tmp/rustup.rs
/tmp/rustup.rs -y
rm /tmp/rustup.rs

echoStatus "Install Cargo prerequisites"
sudo apt install \
	cmake \
	libasound2-dev \
	libclang1 \
	libssl-dev \
	libfreetype6-dev \
	libexpat1-dev \
	libxcb-composite0-dev \
	pkg-config \


echoStatus "Install common Cargo tools"
source "$HOME/.cargo/env"
init rust-install \
	bat \
	bandwhich \
	bottom \
	diffr \
	du-dust \
	exa \
	fd-find \
	git-delta \
	hexyl \
	jless \
	lfs \
	lsd \
	mcfly \
	tokei \
	xcp \


echoStatus "Install Dog"
rust-install --git https://github.com/ogham/dog dog


echoStatus "Install RipGrep + PCRE2 support"
rust-install ripgrep --features pcre2
