#!/bin/bash
# Install Nginx as a HTTP / HTTPS reverse proxy
# REQUIRES: 007-apt-update

source common

init status "Install Nginx via Apt"
curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
init apt-install nginx

init file-set /etc/nginx/nginx.conf <<EOF
pid /var/run/nginx.pid;
worker_processes auto; # 'auto' = Use CPU count as worker count

events {
	worker_connections 4096;
}

http {
	# Upload config {{{
	client_max_body_size 500M;
	# }}}

	# Compression {{{
	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	gzip on;
	gzip_http_version 1.0;
	gzip_comp_level 2;
	gzip_proxied any;
	gzip_min_length  1100;
	gzip_buffers 16 8k;
	gzip_types text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;
	#  }}}

	# Redirect http -> https {{{
	server {
		listen 80;
		return 301 https://$host$request_uri;
	}
	# }}}

	# acme.com {{{
	server {
		listen 443 ssl http2;
		listen [::]:443 ssl http2;
		server_name acme.com;

		ssl_certificate /etc/letsencrypt/live/acme.com/cert.pem;
		ssl_certificate_key /etc/letsencrypt/live/acme.com/privkey.pem;

		location / {
			proxy_pass http://localhost:8001;
			proxy_redirect off;

			proxy_http_version 1.1;
			proxy_set_header Accept-Encoding "";
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}
	# }}}
}
EOF
