#!/bin/bash
# Install Flatpak + basic packages

source common

if [ `INIT bin-available flatpak` == 1 ]; then
	INIT skip "Install Flatpak"
else
	INIT status "Install Flatpak"
	INIT apt-install flatpak

	INIT skip "Configure Flathub"
	flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
fi
