#!/bin/bash
# Setup the automatic MFDC backup process
# Also copies the public key to the MFDC backup server so the backup script can login
# REQUIRES: 000-hostname 001-keygen

source common

if [ -e '/bin/mfdc-backup' ]; then
	echoSkip "Backup script already installed"
	exit 0;
fi

echoStatus "Install backup script"
echo
echo "Connecting to office.mfdc.biz"
echo "You may be asked for the backup server password"
echo
ssh-copy-id backups@office.mfdc.biz

echoStatus "Copy backup script to /bin"
sudo cp bin/mfdc-backup /bin/mfdc-backup
sudo chmod +x /bin/mfdc-backup

echoStatus "Install crontab for backup script"
echo "MAILTO=deamons@mfdc.biz" | sudo tee /var/spool/cron/crontabs/root >/dev/null
echo "SHELL=/bin/sh" | sudo tee -a /var/spool/cron/crontabs/root >/dev/null
echo "@daily /bin/mfdc-backup" | sudo tee -a /var/spool/cron/crontabs/root >/dev/null
