#!/bin/bash
# Install the handy `pipeline` ncurses tool

source common

init status "Install Pipeline prerequisites"
init apt-install \
	libreadline-dev \
	libncurses5-dev \


init status "Clone Pipeline git repo"
init source-clone pipeline https://github.com/codekitchen/pipeline.git

init status "Setup Pipeline"
autoreconf -fi
./configure
make
sudo make install
