#!/bin/bash
# Install ObjectiveFS, setup a mount point and install into fstab

source common

init status "Install ObjectiveFS from Deb"
init apt-install-url 'https://objectivefs.com/user/download/axn2xgkwt/objectivefs_6.8_amd64.deb'

init status "Setup ObjectiveFS"
sudo mount.objectivefs config

grep -s objectivefs /etc/fstab
if [ "$?" == 0 ]; then
	init skip "OFS already configured in /etc/fstab"

	init status "Unmounting OFS in fstab"
	sudo umount -a -t objectivefs
else
	init status "Create OFS filesystem"
	read -p "Enter S3 mountpoint to create (only alpha + dashes): " FS
	sudo mount.objectivefs create "$FS"

	init status "Setup OFS-on-boot"
	read -p "Re-enter OFS passphase to install OFS into fstab: " PASS
	read -p "Enter mount path: " MOUNTPATH
	echo "$PASS" | sudo tee /etc/objectivefs.env/OBJECTIVEFS_PASSPHRASE >/dev/null
	echo "s3://$FS $MOUNTPATH objectivefs  auto,_netdev,mt,noatime,nodiratime 0 0" | sudo tee -a /etc/fstab >/dev/null
fi

init status "Mounting OFS"
sudo mount -a -t objectivefs
