#!/bin/bash
# Install the handy `pipeline` ncurses tool

source common

echoStatus "Install Pipeline prerequisites"
init apt-install \
	libreadline-dev \
	libncurses5-dev \


echoStatus "Clone Pipeline git repo"
init source-clone pipeline https://github.com/codekitchen/pipeline.git

echoStatus "Setup Pipeline"
autoreconf -fi
./configure
make
sudo make install
