#!/bin/bash
# Setup the Zabbix agent
# REQUIRES: 000-hostname

source common

INIT status "Setup Zabbix-Agent"
INIT apt-install-url "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu$(lsb_release -rs)_all.deb"
INIT apt-update
INIT apt-install zabbix-agent


INIT status "Generate Zabbix PSK key"
sudo sh -c "openssl rand -hex 32 > /etc/zabbix/zabbix_agentd.psk"
PSK=`cat /etc/zabbix/zabbix_agentd.psk`

echo
echo "Zabbix agent setup to continue with PSK [name = `hostname`] [PSK = [ $PSK ]]"
echo
echo "Press enter to continue, when this has been noted"
echo
read


echo
echo "Enter upstream Zabbix server address"
read -p "[calculon.mfdc.io] >" ZABBIX_SERVER
if [ -z "$ZABBIX_SERVER" ]; then
	ZABBIX_SERVER=calculon.mfdc.io
fi
echo

INIT status "Configure Zabbix-agent"
THIS_HOST=`hostname`
INIT file-set "/etc/zabbix/zabbix_agentd.conf" <<EOF
PidFile=/var/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix-agent/zabbix_agentd.log
LogFileSize=128


Server=$ZABBIX_SERVER
ServerActive=$ZABBIX_SERVER
Hostname=$THIS_HOST
TLSConnect=psk
TLSAccept=psk
TLSPSKIdentity=$THIS_HOST
TLSPSKFile=/etc/zabbix/zabbix_agentd.psk
EOF

sudo systemctl restart zabbix-agent
sudo systemctl enable zabbix-agent


INIT status "Installing Firewall rule"
sudo ufw allow 10050/tcp
