#!/bin/bash
# Setup the Zabbix agent
# REQUIRES: 000-hostname

source common

INIT status "Setup Zabbix-Agent"
INIT apt-install-url "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
INIT apt-update
INIT apt-install zabbix-agent


INIT status "Generate Zabbix PSK key"
sudo sh -c "openssl rand -hex 32 > /etc/zabbix/zabbix_agentd.psk"
PSK=`cat /etc/zabbix/zabbix_agentd.psk`

echo
echo "Zabbix agent setup to continue with PSK [name = `hostname`] [PSK = [ $PSK ]]"
echo
echo "Press enter to continue, when this has been noted"
echo
read


INIT status "Configure Zabbix-agent"
INIT config-set-ini "/etc/zabbix/zabbix_agentd.conf" "Server" `hostname`
INIT config-set-ini "/etc/zabbix/zabbix_agentd.conf" "ServerActive" `hostname`
INIT config-set-ini "/etc/zabbix/zabbix_agentd.conf" "TLSConnect" "psk"
INIT config-set-ini "/etc/zabbix/zabbix_agentd.conf" "TLSAccept" "psk"
INIT config-set-ini "/etc/zabbix/zabbix_agentd.conf" "TLSPSKIdentity" `hostname`
INIT config-set-ini "/etc/zabbix/zabbix_agentd.conf" "TLSPSKFile" "/etc/zabbix/zabbix_agentd.psk"


INIT status "Installing Zabbit agent"
sudo systemctl restart zabbix-agent
sudo systemctl enable zabbix-agent


INIT status "Installing Firewall rule"
sudo ufw allow 10050/tcp
