#!/bin/bash
# Install the handy `pipeline` ncurses tool

source common

echoStatus "Install prerequisites"
sudo apt install -y libreadline-dev libncurses5-dev

echoStatus "Clone Pipeline git repo"
cd
if [ ! -d "src" ]; then
	mkdir src
fi
cd src
git clone --depth 1 https://github.com/codekitchen/pipeline.git
cd pipeline

echoStatus "Setup Pipeline"
autoreconf -fi
./configure
make
sudo make install
