#!/bin/bash
# Install Duplicity + Duply
# REQUIRES: 000-hostname

source common


INIT apt-install --lazy --header "Installing Duplicity + Duply build pre-requisites" wget


INIT status "Install Duplicity"
INIT apt-install duplicity


INIT status "Install Duply"
INIT go-src
wget 'https://sourceforge.net/projects/ftplicity/files/duply%20%28simple%20duplicity%29/2.3.x/duply_2.3.1.tgz/download' -O duply.tar.gz
tar xvfz duply.tar.gz
rm duply.tar.gz
cd duply*/
cp duply /usr/local/bin
cd ..
rm -r duply*


INIT status "Configure Duply"
mkdir /etc/duply
chmod 700 /etc/duply


INIT status "Manual setup"
echo "Recommended settings:"
echo "* Create basic profile: > duply serverBackup create"
echo "* Change TARGET: TARGET='sftp://backups@zapp.mfdc.biz/backups/$HOST'"
