#!/bin/bash
# Setup the Zabbix agent

source "$(dirname "${BASH_SOURCE[0]}")/./common"

INIT status "Install latest Ghostty"
sudo add-apt-repository -y ppa:mkasberg/ghostty-ubuntu
INIT apt-update
INIT apt-install ghostty
