#!/bin/bash
# Setup the automatic MFDC Mindstate backup process
# REQUIRES: 000-hostname 001-keygen

source common

INIT status "Install Common Apt repos"
INIT apt-install inxi

INIT status "Install Mindstate NPM"
INIT npm-install mindstate

INIT status "Configure Mindstate"
# NOTE: The mindstate setup process will also install other NPM plugin modules + copy the SSH key to the backup server
sudo mindstate --setup

INIT status "Install Mindstate crontab"
echo "MAILTO=daemons@mfdc.biz" | sudo tee /var/spool/cron/crontabs/root >/dev/null
echo "SHELL=/bin/sh" | sudo tee -a /var/spool/cron/crontabs/root >/dev/null
echo "@daily mindstate --backup" | sudo tee -a /var/spool/cron/crontabs/root >/dev/null
