#!/bin/bash
# Setup the automatic MFDC Mindstate backup process
# REQUIRES: 000-hostname 001-keygen

source common

init status "Install Common Apt repos"
init apt-install inxi

init status "Install Mindstate NPM"
init npm-install mindstate

init status "Configure Mindstate"
# NOTE: The mindstate setup process will also install other NPM plugin modules + copy the SSH key to the backup server
sudo mindstate --setup

init status "Install Mindstate crontab"
echo "MAILTO=daemons@mfdc.biz" | sudo tee /var/spool/cron/crontabs/root >/dev/null
echo "SHELL=/bin/sh" | sudo tee -a /var/spool/cron/crontabs/root >/dev/null
echo "@daily mindstate --backup" | sudo tee -a /var/spool/cron/crontabs/root >/dev/null
