#!/bin/bash
# Install Wezterm terminal emulator
# REQUIRES: 200-rust

source common

INIT source-clone "wezterm" https://github.com/wez/wezterm.git

INIT status "Installing dependencies"
./get-deps


INIT status "Building Wezterm"
cargo clean
cargo build --release
