#!/bin/bash
# Install privateinternetaccess.com VPN setup for OpenVPN
# REQUIRES: 007-apt-update

source common

echoStatus "Install OpenVPN"

./utils/apt-install \
	openvpn \
	network-manager-openvpn \
	network-manager-openvpn-gnome \


echoStatus "Install PIA open VPN setup"

cd /etc/openvpn
sudo wget https://www.privateinternetaccess.com/openvpn/openvpn.zip
sudo unzip openvpn.zip
sudo rm openvpn.zip
sudo /etc/init.d/openvpn restart
