#!/bin/bash
# Install various games
# REQUIRES: 007-apt-update

source common

INIT status "Install GetDeb key for APT"
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -

INIT status "Install GetDeb repo for APT"
echo 'deb http://archive.getdeb.net/ubuntu/ xenial-getdeb games' | sudo tee /etc/apt/sources.list.d/getdeb.list

INIT status "Update APT"
sudo apt-get update

INIT status "Install common games"
INIT apt-install warsow
