#!/bin/bash
# Install various games
# REQUIRES: 007-apt-update

source common

init status "Install GetDeb key for APT"
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -

init status "Install GetDeb repo for APT"
echo 'deb http://archive.getdeb.net/ubuntu/ xenial-getdeb games' | sudo tee /etc/apt/sources.list.d/getdeb.list

init status "Update APT"
sudo apt-get update

init status "Install common games"
init apt-install warsow
