#!/bin/bash
# Install Crashplan on a Linux server

source common

INIT status "Install Crashplan"

echo "FIXME: Need installation process - this file currently only supports SystemD setup component"

exit 1


INIT status "Setup SystemD service"

INIT file-set /etc/systemd/system/crashplan.service <<EOF
[Unit]
Description=CrashPlan service
After=network.target

[Service]
User=root
Group=root
ExecStart=/usr/local/crashplan/bin/service.sh start
ExecStop=/usr/local/crashplan/bin/service.sh stop
Restart=on-failure
Type=forking

[Install]
WantedBy=default.target
EOF

sudo systemctl daemon-reload
sudo systemctl start crashplan
sudo systemctl enable crashplan
