#!/bin/bash
# Various fixes for Digital Ocean minimal VMs
# Mainly this is just Swap file hacks so NPM doesn't kill itself when searching in <512mb RAM

source common

echoStatus "Setting up Swap file
touch /var/swap.img
chmod 0600 /var/swap.img
dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
mkswap /var/swap.img
swapon /var/swap.img
echo "/var/swap.img    none    swap    sw    0    0" >> /etc/fstab

echoSatus "Setting up system Swappiness"
sysctl -w vm.swappiness=30
