#!/bin/bash
# Install Wezterm terminal emulator

source common

INIT source-clone "wezterm" https://github.com/wez/wezterm.git
INIT go-src wezterm

INIT status "Installing dependencies"
./get-deps
cargo install cargo-deb


INIT status "Building Wezterm"
cargo clean
# NOTE: `--no-default-features` + `--features vendored-fonts` excludes Wayland builds which often causes issues with non-edge versions of Ubuntu - MC 2024-02-07
cargo build \
	--release \
	--no-default-features \
	--features vendored-fonts \


INIT status "Installing Wezterm DEB"
NOW=`date '+%Y%m%d%H%M%S'`

cargo deb \
	--verbose \
	--fast \
	--install \
	--package wezterm \
	--deb-revision "$NOW"

cargo deb \
	--verbose \
	--fast \
	--install \
	--package wezterm-gui \
	--deb-revision "$NOW"
