#!/bin/bash
# Install Amazon Galcier Sync (mt-aws-glacier)
# REQUIRES: 007-apt-update

source common

init status "Install Glacier PPA"
sudo add-apt-repository -y ppa:vsespb/mt-aws-glacier

# Have to replace the PPA version with Precise as this was the last one supported
echo 'deb http://ppa.launchpad.net/vsespb/mt-aws-glacier/ubuntu precise main' | sudo tee /etc/apt/sources.list.d/vsespb-ubuntu-mt-aws-glacier-wily.list >/dev/null

sudo apt-get update

init status "Install Glacier Perl Library"
init apt-install libapp-mtaws-perl
