#!/bin/bash
# Install Wezterm terminal emulator
# REQUIRES: 200-rust

source common

init source-clone "wezterm" https://github.com/wez/wezterm.git

echoStatus "Installing dependencies"
./get-deps


echoStatus "Building Wezterm"
cargo clean
cargo build --release
