#!/bin/bash
# Install various games
# REQUIRES: 007-apt-update

source common

echoStatus "Install GetDeb key for APT"
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -

echoStatus "Install GetDeb repo for APT"
echo 'deb http://archive.getdeb.net/ubuntu/ xenial-getdeb games' | sudo tee /etc/apt/sources.list.d/getdeb.list

echoStatus "Update APT"
sudo apt-get update

echoStatus "Install common games"
./utils/apt-install warsow
