#!/bin/bash
# Install privateinternetaccess.com VPN setup for OpenVPN

source common

INIT status "Install OpenVPN"
INIT apt-install \
	openvpn \
	network-manager-openvpn \
	network-manager-openvpn-gnome \


INIT status "Install PIA open VPN setup"
cd /etc/openvpn
sudo wget https://www.privateinternetaccess.com/openvpn/openvpn.zip
sudo unzip openvpn.zip
sudo rm openvpn.zip
sudo /etc/init.d/openvpn restart
