#!/bin/bash
# Clean up temporary files to free up space

source "$(dirname "${BASH_SOURCE[0]}")/./common"

INIT status "Removing temporary files (>3 days)"
INIT tolerate find /tmp -type f -mtime +3 -delete 2>/dev/null

INIT status "Removing temporary Cargo install profiles"
INIT tolerate rm -r /tmp/*cargo* 2>/dev/null

INIT status "Clean apt cache"
sudo apt autoclean

INIT status "Vacuum kernel logs"
sudo journalctl --vacuum-time=3d

CLEAN_DIRS=(
	"$HOME/.cache"
	"$HOME/.cargo/registry"
	"$HOME/.node-gyp"
	"$HOME/.rustup"
	"$HOME/.local/share/Trash"
	"/home/*/.rust/tmp"
)

INIT status "Clean directories"
shopt -s nullglob
for PATTERN in "${CLEAN_DIRS[@]}"; do
	for DIR in $PATTERN; do
		[ -d "$DIR" ] || continue
		INIT status "Removing $DIR"
		sudo rm -rf "$DIR"
	done
done
shopt -u nullglob

if [ `INIT bin-available flatpak` == 1 ]; then
	INIT status "Clean Flatpak unused packages"
	flatpak uninstall --unused
fi

if [ `INIT bin-available npm` == 1 ]; then
	INIT status "Clean NPM cache"
	npm cache clean --force
fi

if [ `INIT bin-available pnpm` == 1 ]; then
	INIT status "Clean PNPM cache"
	pnpm store prune
fi

if [ `INIT bin-available yarn` == 1 ]; then
	INIT status "Clean Yarn cache"
	yarn cache clean
fi

if [ `INIT bin-available cargo-cache` == 1 ]; then
	INIT status "Clean Cargo cache"
	cargo cache -a
fi

if [ `INIT bin-available docker` == 1 ]; then
	INIT status "Clean Docker cache"
	docker system prune --force
fi
