#!/bin/bash
# Common functionality library imported by all other scripts in this directory

# Declare we have included this file at least once (used by the source includes in `./utils/*`
export INIT=1

# Force all scripts to use non-interactive DPKG prompts on install
export DEBIAN_FRONTEND=noninteractive

# Import the config
source config

# Call a utility function as sourced within the current shell
function INIT {
	UTIL="$1"
	shift
	"$INIT_HOME/utils/$UTIL" "$@"
}

# Quit on any error
set -e
