#!/bin/bash
# Common functionality library imported by all other scripts in this directory

# Force all scripts to use non-interactive DPKG prompts on install
export DEBIAN_FRONTEND=noninteractive

# Call a utility function as sourced within the current shell
function init {
	UTIL=$1
	shift
	source "./utils/$UTIL" "$@"
}

# Quit on any error
set -e
