#!/bin/bash
# Setup this box as a Node server

# Quit on any error
set -e

./000-hostname
./001-keygen
./007-apt-update
./010-apt-auto
./010-apt-server
./020-lamp-stack
./030-mail
./040-apache-config
./040-apache-symlink
./090-monit
./090-newrelic-php
./500-mfdc-mindstate
./900-deploy-github
