#!/bin/bash
# Setup this box as a Node server

source common

INIT run \
	000-hostname \
	001-keygen \
	001-locales \
	001-needrestart \
	001-timezone \
	003-hosting \
	003-journald \
	005-pkg-rm \
	007-apt-update \
	010-apt-auto \
	010-apt-server \
	015-secure-ssh \
	015-tmux \
	020-firewall \
	020-mongo \
	020-node \
	030-fix-motd \
	040-pm2 \
	050-zsh \
	090-btop \
	090-dtrx \
	090-fzf \
	100-letsencrypt \
	200-nginx \
	200-rust \
	201-rust-pkgs \
	999-clean \
