#!/bin/bash
# Setup this box as a Node server

source common

INIT run \
	000-hostname \
	001-keygen \
	001-locales \
	001-needrestart \
	001-timezone \
	003-journald \
	007-apt-update \
	010-apt-auto \
	010-apt-server \
	020-lamp-stack \
	030-mail \
	040-apache-config \
	040-apache-symlink \
	090-dtrx \
	090-monit \
