#!/bin/bash
# Setup this box as a generic server

# Quit on any error
set -e

./000-hostname
./001-keygen
./005-digital-ocean-minimal
./005-pkg-rm
./007-apt-update
./010-apt-auto
./010-apt-server
./020-node
./020-firewall
./030-fix-motd
./030-mail
