#!/bin/bash
# Setup this box as a regular Desktop machine running XFCE

# Quit on any error
set -e

./000-hostname
./001-keygen
./005-pkg-rm
./007-apt-update
./010-apt-desktop
./010-apt-server
./015-apt-xfce
./015-chrome
./020-docker
./020-lamp-stack
./020-node
./030-fix-motd
./040-apache-config
./040-mk-inc
./040-screen-config
./090-neovim
./090-root-bashrc
