#!/bin/bash
# Setup this box as a Node server

# Quit on any error
set -e

./000-hostname
./001-keygen
./007-apt-update
./010-apt-auto
./010-apt-server
./020-node
./020-mongo3
./020-firewall
./030-fix-motd
./030-mail
./500-mfdc-mindstate
./900-deploy-github
