#!/bin/bash
# Install one or more URL deb packages
# Usage: ./utils/apt-install-url <urls...>

[ -z "$INIT" ] && source common

init go-src

if [ ! -d "deb" ]; then
	mkdir deb
	cd deb
else
	init status "Erasing existing Source directory"
	rm -r deb
	mkdir deb
	cd deb
fi

init file-download-url "$@"

init status "Installing .DEB files"
dpkg -i *.deb

init status "Cleaning up .DEB files"
cd "$INIT_SRC"
rm -r deb

# Go back to base
cd "$INIT_HOME"
