#!/bin/bash
# Install a release from a GitHub URL
#
# Usage: ./utils/apt-install-github-release [--lazy] [--header text] <owner/repo>
#
# <owner/repo>             The GitHub Owner/repo combo. e.g. 'acme/widget'
#
# -b, --lazy-bin <name>    Exit politely if the given name is avaiable as a binary executable
#

[ -z "$INIT_READY" ] && source common

# Argument processing {{{
IS_LAZY_BIN=0
BIN_NAME=""
PARAMS=()
while (( "$#" )); do
	case "$1" in
		-b|--lazy-bin)
			IS_LAZY_BIN=1
			BIN_NAME="$2"
			shift
			shift
			;;
		--) # end argument parsing
			shift
			break
			;;
		-*|--*=) # unsupported flags
			PARAMS+=("$1")
			shift
			;;
		*) # preserve positional arguments
			PARAMS+=("$1")
			shift
			;;
	esac
done

GITHUB_REPO="${PARAMS[0]}"
GITHUB_ASSET="${PARAMS[1]}"
# }}}

# Lazy mode {{{
if [[ "$IS_LAZY_BIN" == 1 && `INIT bin-available "${BIN_NAME}"` == 1 ]]; then
	# Bin is available -  do nothing
	exit 0
fi
# }}}

INIT go-src

INIT status "Installing latest version of GitHub ${GITHUB_REPO}"

GITHUB_URL=`wget -c -t 0 -T 30 "https://api.github.com/repos/${GITHUB_REPO}/releases" -qO- | grep browser_download_url | grep '64[.]deb' | head -n 1 | cut -d '"' -f 4`

INIT apt-install-url "${GITHUB_URL}"
