#!/bin/bash
# Install one or more URL deb packages
# Usage: ./utils/apt-install-url <urls...>

source common

init apt-install --lazy --header "Installing Aria2c downloader" aria2

init go-src
if [ ! -d "deb" ]; then
	mkdir deb
	cd deb
else
	init status "Erasing existing Source directory"
	rm -r deb
	mkdir deb
	cd deb
fi

if [ "${#@}" == 1 ]; then
	init status "Downloding $1"
	wget "$@"
else
	init status "Downloading ${#@} .DEB URLS"
	aria2c --max-concurrent-downloads=4 "$@"
fi

init status "Installing .DEB files"
dpkg -i *.deb

init status "Cleaning up .DEB files"
cd "$INIT_SRC"
rm -r deb
