#!/bin/bash
# Remove a series of APT packages
#
# Usage: ./utils/apt-remove [--lazy] [--header text] <packages...>
#
# -l, --lazy                Exit politely if all packages are already installed
#
# -h, --header <text>       Print the given header only if an action is taken
#
# -m, --mode <remove|purge> Change the mode to use when removing

[ -z "$INIT_READY" ] && source common

# Argument processing {{{
MODE="remove"
IS_LAZY=0
HEADER=""
PARAMS=""
while (( "$#" )); do
	case "$1" in
		-l|--lazy)
			IS_LAZY=1
			shift
			;;
		-h|--header)
			HEADER="$2"
			shift
			shift
			;;
		-m|--mode)
			MODE="$2"
			shift
			shift
			;;
		--) # end argument parsing
			shift
			break
			;;
		-*|--*=) # unsupported flags
			if [ "$ACTION" == "auto" ]; then
				PARAMS="$PARAMS $1"
				shift
			else
				echo "Error: Unsupported flag $1" >&2
				exit 1
			fi
			;;
		*) # preserve positional arguments
			PARAMS="$PARAMS $1"
			shift
			;;
	esac
done
PARAMS=${PARAMS## } # remove leading spaces
# }}}

if [ "$IS_LAZY" == 1 ]; then
	# Lazy mode {{{
	NEED_REMOVE=0
	if [ `INIT apt-has "$@"` == 1 ]; then
		NEED_REMOVE=1
	fi
	# }}}
fi

# Actually do something?
if [[ "$IS_LAZY" == 2 || "$NEED_REMOVE" == 1 ]]; then

	# Output header if we got this far (with --lazy) or if the user asked for one
	if [ ! -z "$HEADER" ]; then
		INIT status "$HEADER"
	fi

	sudo apt "$MODE" -y $PARAMS
fi
