#!/bin/bash
# Faults if isnt installed within the current path, otherwise exits normally
# Usage: ./utils/bin-available <bin>
#
# @example test if the "foobar" binary is available within a Bash If
# if [ `./utils/bin-available dtrx` ]; then
#   echo "Is available"
# fi


if which "$1" >/dev/null 2>/dev/null; then
	exit 0
else
	exit 1
fi

