#!/bin/bash
# Install a Rust packages, including INIT of Rust + Cargo if necessary
# Usage: ./utils/cargo-install <packages...>

[ -z "$INIT" ] && source common

if [ `INIT bin-available cargo` == 0 ]; then
	echo "Need to install Rust first"
	INIT run 200-rust
fi

cargo install "$@"
