#!/bin/bash
# Install a Rust packages, including INIT of Rust + Cargo if necessary
# Usage: ./utils/cargo-install <packages...>

source "$(dirname "${BASH_SOURCE[0]}")/../common"

if [ `INIT bin-available cargo-cache` == 0 ]; then
	INIT status "Install pre-requsite: cargo-cache"
	cargo install cargo-cache
fi

# Set Cargo tmp directory to local home as /tmp is limited to 500mb on Ubuntu 26.04 default installs
export CARGO_TARGET_DIR="$HOME/.cargo/tmp"
cargo install "$@"

INIT status "Clear cargo cache"
# Try to recover some disk space post compile of cargo-binstall
cargo cache -a
