#!/bin/bash
# Set a simple INI setting within a file
# Usage: INIT config-set <file> <key> <value>

[ -z "$INIT_READY" ] && source common

INIT apt-install --lazy --header "Installing Perl Pre-requisite" perl

FILE=$1
KEY=$2
VALUE=$3
DATE=`date '+%Y-%m-%dT%H:%M:%SZ%z'`

if grep -q "$KEY\s*=" "$FILE"; then
	# Update existing setting
	sudo perl -pi -e "my \$key = quotemeta('$KEY'); my \$val = '$VALUE'; s!^\#?\s*\$key\s*=.*\$!\$key=\$val!" "$FILE"
else
	# Append setting

INIT file-set "$FILE" --append <<EOF

# Added by INIT process on $DATE
$KEY=$VALUE

EOF
fi
