#!/bin/bash
# Return a '1' if a given file path exists and matches a grep expression, otherwise '0'
# Usage: ./utils/file-grep-matches <file> <grep>
#
# @example test if the "foo" exists within /tmp/file.txt
# if [ `INIT file-grep-matches /tmp/file.txt "foo"` == 1 ]; then
#   echo "Is a match"
# fi

[ -z "$INIT_READY" ] && source common

if grep -q "$2" "$1"; then
	echo "1"
else
	echo "0"
fi
