#!/bin/bash
# Download one or more URLs into the current directory
#
# Usage: ./utils/file-install-url [--header text] [--tool tool="auto"] <urls...>
#
# -h, --header <text> Print the given header only if an action is taken
#
# -t, --tool <tool>   Use the specified downloader tool to download files
#

[ -z "$INIT" ] && source common

# Argument processing {{{
TOOL="auto"
HEADER=""
PARAMS=()
while (( "$#" )); do
	case "$1" in
		-t|--tool)
			TOOL="$2"
			shift
			shift
			;;
		-h|--header)
			HEADER="$2"
			shift
			shift
			;;
		--) # end argument parsing
			shift
			;;
		-*|--*=) # unsupported flags
			PARAMS+=("$1")
			shift
			;;
		*) # preserve positional arguments
			PARAMS+=("$1")
			shift
			;;
	esac
done
# }}}

# Calculate what header to use {{{
if [ -z "$HEADER" ]; then
	if [ "${#PARAMS[@]}" == 1 ]; then
		INIT status "Downloading URL ${PARAMS[0]}"
	else
		INIT status "Downloading ${#PARAMS[@]} URLS"
	fi
fi
# }}}

# Calculate what tool to use (if in 'auto' mode) {{{
if [ "${#PARAMS[@]}" == 1 ]; then
	TOOL="wget"
else
	TOOL="aria2"
fi
# }}}

# Download URLs with specified tool {{{
case "${TOOL}" in
	aria2)
		INIT apt-install --lazy --header "Installing Aria2c downloader" aria2
		aria2c --force-sequential --max-concurrent-downloads=4 "${PARAMS[@]}"
		;;
	wget)
		INIT apt-install --lazy --header "Installing Wget downloader" wget
		wget "${PARAMS[@]}"
		;;
	*)
		echo "Unknown tool to download URLs with '${TOOL}'"
		exit 1
		;;
esac
# }}}
