#!/bin/bash
# Change directory back to the base Init directory
# This gets run after each `INIT run` or other commands that change directory temporarily

source "$(dirname "${BASH_SOURCE[0]}")/../common"

cd "$INIT_HOME"
