#!/bin/bash
# Ensure the INIT_SRC directory exists + CD to it
# Usage: INIT go-src [subdir]

[ -z "$INIT_READY" ] && source common

if [ ! -d "$INIT_SRC" ]; then
	mkdir -p "$INIT_SRC"
fi

cd "$INIT_SRC"

if [ ! -z "$1" ]; then
	if [ ! -d "$1" ]; then
		mkdir "$1"
	fi
	cd "$1"
fi
