#!/bin/bash
# Install a series of NPM packages
# Usage: ./utils/npm-install <packages...>

[ -z "$INIT_READY" ] && source common

if [ `INIT bin-available npm` == 0 ]; then
	INIT status "Need to install Node + NPM"
	INIT run 020-node
fi

sudo npm install -g "$@"
