#!/bin/bash
# Install a series of NPM packages
# Usage: ./utils/npm-install <packages...>

[ -z "$INIT" ] && source common

if [ `init bin-available npm` == 0 ]; then
	init status "Need to install Node + NPM"
	init run 020-node
fi

sudo npm install -g "$@"
