#!/bin/bash
# Install a series of packages via PIP (w/Python3)
# Usage: ./utils/pip-install <packages...>

[ -z "$INIT_READY" ] && source common

if [ `which 'node' >/dev/null; echo "$?"` == 0 ]; then
	INIT apt-install --header "Installing Python3 + PIP" \
		python3 \
		python3-pip \

	INIT status "Upgrade Pip3 to latest version"
	pip3 install --upgrade pip
fi

if [[ ! -O "$HOME/.cache" || ! -O "$HOME/.cache/pip" ]]; then
	INIT status "Correcting .cache permissions"
	sudo chown -R "$USER" "$HOME/.cache"
fi

pip3 install --quiet --no-cache-dir --root-user-action=ignore "$@"
