#!/bin/bash
# Install a series of packages via PIP (w/Python3)
# Usage: ./utils/pip-install <packages...>

source common

init apt-install --lazy python3-pip

if [[ ! -O "$HOME/.cache" || ! -O "$HOME/.cache/pip" ]]; then
	init status "Correcting .cache permissions"
	sudo chown -R "$USER" "$HOME/.cache"
fi

pip3 install --quiet --no-cache-dir "$@"
