#!/bin/bash
# Run a step or steps of the init/ directory CDing back when completed
# Usage: ./utils/run <tasks...>

[ -z "$INIT_READY" ] && source common

for TASK in "$@"; do
	cd "$INIT_HOME"
	if [ -x "$INIT_HOME/$TASK" ]; then
		"$INIT_HOME/$TASK"
	else
		echo "Invalid run unit '${TASK}'"
		exit 1
	fi
done
