#!/bin/bash
# Run a step or steps of the init/ directory CDing back when completed
# Usage: ./utils/run <tasks...>

[ -z "$INIT" ] && source common

for TASK in "$@"; do
	cd "$INIT_HOME"
	source "./$TASK"
done
