#!/bin/bash
# Return a '1' if a service exists, even if it is disabled
# Usage: ./utils/service-available <name>
#
# @example test if the "foo" service is available or known
# if [ `./utils/service-available foo` == 1 ]; then
#   echo "Is available"
# fi

[ -z "$INIT" ] && source common

if systemctl status "$1" >/dev/null 2>&1; then
	echo '1'
else
	echo '0'
fi
