#!/bin/bash
# Simple status reporter to display a status step being skipped
# Usage: ./utils/skip <message>

source "$(dirname "${BASH_SOURCE[0]}")/../common"

echo
echo -ne "\e[30m\e[1m ✘ "
echo -n "$@"
echo -e "\e[0m"
