#!/bin/bash
# Install a series of Snap packages, installing Snap if its required
# Usage: ./utils/snap-install <packages...>

[ -z "$INIT" ] && source common

if [ `init bin-available snap` == 0 ]; then
	init status "Need to install Snap first"
	init run 015-snap
fi

snap install "$@"
