#!/bin/bash
# Install a series of Snap packages, installing Snap if its required
# Usage: ./utils/snap-install <packages...>

[ -z "$INIT" ] && source common

if [ `INIT bin-available snap` == 0 ]; then
	INIT status "Need to install Snap first"
	INIT run 015-snap
fi

snap install "$@"
