#!/bin/bash
# Install a series of Snap packages, installing Snap if its required
# Usage: ./utils/snap-install <packages...>

source ../common

if [ ! `init bin-available snap` ]; then
	init status "Need to install Snap first"
	sudo apt update 015-snap
fi

snap install "$@"
