#!/bin/bash
# Clone a Git-accessible repo into ~/src creating logical directories as needed
#
# This script will:
#    - Create ~/src if its missing
#    - Clone or update the repo (minimal depth)
#    - CD into the directory
#    - Clone or update submodules (if any; minimal depth)
#
# Usage: ./utils/source-clone <alias> <git-url>
#
# @example Clone the DTRX repo
# ./utils/source-clone dtrx https://github.com/brettcs/dtrx.git

source common

if [ ! -d "$HOME/src" ]; then
	mkdir -p "$HOME/src"
fi

cd "$HOME/src"

if [ -d "$1" ]; then
	echoStatus "Updating ${1^} source"
	cd "$1"
	git pull

	if [ -e '.gitmodules' ]; then
		echoStatus "Updating ${1^} Submodules"
		git submodule update --recursive
	fi
else
	echoStatus "Cloning ${1^} source"
	git clone --recursive --depth=1 --shallow-submodules "$2" "$1"
	cd "$1"
fi
