#!/bin/bash
# Simple status reporter to display a status step
# Usage: ./utils/status <message>

source "$(dirname "${BASH_SOURCE[0]}")/../common"

echo -ne "\n\e[34m\e[1m"
echo -e "$@"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' '~'
echo -ne "\e[0m"
